#import <Foundation/Foundation.h>

static NSString *OnDeviceAgentPageHTML(void)
{
  static NSString *const kOnDeviceAgentPageHTMLHead =
    @"<!doctype html>\n"
    @"<html>\n"
    @"<head>\n"
    @"  <meta charset=\"utf-8\" />\n"
    @"  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, viewport-fit=cover\" />\n"
    @"  <title>iOS WDA On‑Device Agent</title>\n"
    @"  <style>\n";

  static NSString *const kOnDeviceAgentPageCSS =
    @"    :root{color-scheme:light dark;--bg:#fff;--fg:#111;--muted:#666;--card:#f6f6f6;--border:#ccc;--primary:#0a84ff;--danger:#ff3b30;--radius:12px;}\n"
    @"    @media (prefers-color-scheme: dark){:root{--bg:#0b0b0c;--fg:#f2f2f2;--muted:#b0b0b0;--card:#1c1c1e;--border:#3a3a3c;--primary:#0a84ff;--danger:#ff453a;}}\n"
    @"    html,body{height:100%;}\n"
    @"    body{font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica,Arial,sans-serif;background:var(--bg);color:var(--fg);margin:0;padding:16px;padding-left:max(16px,env(safe-area-inset-left));padding-right:max(16px,env(safe-area-inset-right));padding-top:max(16px,env(safe-area-inset-top));padding-bottom:max(16px,env(safe-area-inset-bottom));}\n"
    @"    .container{max-width:900px;margin:0 auto;}\n"
    @"    h2{margin:0 0 8px 0;font-size:20px;}\n"
    @"    h3{margin:16px 0 8px 0;font-size:16px;}\n"
    @"    label{display:block;margin-top:12px;font-weight:600;}\n"
    @"    .label-row{display:flex;align-items:center;justify-content:space-between;gap:10px;margin-top:12px;flex-wrap:wrap;}\n"
    @"    .label-row > label:not(.check){margin:0;font-weight:600;}\n"
    @"    .label-row > .check{margin-top:0;}\n"
    @"    .label-actions{display:flex;align-items:center;justify-content:flex-end;gap:8px;flex-wrap:wrap;}\n"
    @"    .btn-sm{min-height:32px;padding:6px 10px;border-radius:10px;flex:0 0 auto;font-size:13px;}\n"
    @"    input,textarea,select{width:100%;padding:10px 12px;border:1px solid var(--border);border-radius:var(--radius);box-sizing:border-box;font-family:inherit;font-size:16px;background:var(--card);color:inherit;}\n"
    @"    input:focus,textarea:focus,select:focus{outline:none;border-color:var(--primary);box-shadow:0 0 0 3px rgba(10,132,255,0.25);}\n"
    @"    textarea{min-height:120px;resize:vertical;}\n"
    @"    .mono{font-family:ui-monospace,SFMono-Regular,Menlo,Monaco,Consolas,\"Liberation Mono\",\"Courier New\",monospace;}\n"
    @"    .row{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px;}\n"
    @"    @media (max-width: 680px){.row{grid-template-columns:1fr;}}\n"
    @"    .actions{display:flex;flex-wrap:wrap;gap:10px;margin-top:12px;}\n"
    @"    button{min-height:44px;padding:10px 14px;border:0;border-radius:12px;flex:1 1 120px;}\n"
    @"    .primary{background:var(--primary);color:#fff;}\n"
    @"    .danger{background:var(--danger);color:#fff;}\n"
    @"    .ghost{background:var(--card);color:inherit;border:1px solid var(--border);}\n"
	    @"    .muted{color:var(--muted);font-size:13px;line-height:1.45;}\n"
	    @"    .callout{margin-top:10px;border:1px solid var(--border);background:var(--card);border-radius:var(--radius);padding:10px 12px;}\n"
	    @"    .callout-row{display:flex;align-items:flex-start;justify-content:space-between;gap:10px;}\n"
	    @"    .callout-text{font-size:13px;line-height:1.45;color:var(--muted);}\n"
	    @"    .callout-text code{font-size:12px;}\n"
	    @"    .callout-btn{min-height:32px;padding:6px 10px;border-radius:10px;flex:0 0 auto;font-size:13px;}\n"
    @"    .error{color:var(--danger);font-size:13px;line-height:1.45;margin-top:10px;white-space:pre-wrap;}\n"
    @"    input.invalid,textarea.invalid,select.invalid{border-color:var(--danger);box-shadow:0 0 0 3px rgba(255,59,48,0.18);}\n"
    @"    .check{display:flex;align-items:center;gap:10px;margin-top:10px;user-select:none;}\n"
    @"    .check input{width:auto;transform:scale(1.15);}\n"
    @"    code{font-family:ui-monospace,SFMono-Regular,Menlo,Monaco,Consolas,\"Liberation Mono\",\"Courier New\",monospace;font-size:13px;background:var(--card);padding:2px 6px;border-radius:8px;overflow-wrap:anywhere;}\n"
    @"    pre{background:var(--card);border:1px solid var(--border);padding:10px;border-radius:var(--radius);white-space:pre-wrap;overflow-wrap:anywhere;word-break:break-word;max-height:40vh;overflow:auto;-webkit-overflow-scrolling:touch;font-size:16px;line-height:1.35;}\n"
    @"    #system_prompt{font-size:16px;line-height:1.35;min-height:260px;}\n"
    @"    .placeholder-grid{display:grid;grid-template-columns:auto 1fr;gap:6px 10px;align-items:start;margin-top:6px;}\n"
    @"    .placeholder-grid .ex{overflow-wrap:anywhere;word-break:break-word;}\n"
    @"    @media (max-width: 520px){.placeholder-grid{grid-template-columns:1fr;}}\n"
    @"    button:disabled{opacity:0.55;}\n"
    @"    .chips{display:flex;flex-wrap:wrap;gap:8px;margin-top:10px;}\n"
    @"    .chip{font-size:12px;line-height:1.2;padding:5px 10px;border-radius:999px;border:1px solid var(--border);background:var(--card);}\n"
    @"    .chip.ok{border-color:rgba(10,132,255,0.35);}\n"
    @"    .chip.bad{border-color:rgba(255,59,48,0.35);color:var(--danger);}\n"
    @"    .readiness-detail{white-space:pre-wrap;}\n"
    @"    .chat{display:flex;flex-direction:column;gap:10px;}\n"
    @"    .step-card{border:1px solid var(--border);background:var(--card);border-radius:var(--radius);overflow:hidden;}\n"
    @"    .step-card > summary{cursor:pointer;list-style:none;padding:10px 12px;font-weight:600;}\n"
    @"    .step-card > summary::-webkit-details-marker{display:none;}\n"
    @"    .step-card[open] > summary{border-bottom:1px solid var(--border);}\n"
    @"    .step-body{padding:10px 12px;display:flex;flex-direction:column;gap:10px;}\n"
    @"    .shot{width:100%;border:1px solid var(--border);border-radius:var(--radius);display:block;}\n"
    @"    .msg{border:1px solid var(--border);border-radius:var(--radius);background:var(--bg);padding:10px 10px;}\n"
    @"    .msg-hdr{font-size:12px;color:var(--muted);margin-bottom:6px;display:flex;gap:8px;flex-wrap:wrap;}\n"
    @"    .msg pre{background:transparent;border:0;padding:0;margin:0;max-height:none;overflow:visible;font-size:15px;line-height:1.35;}\n"
    @"    details.raw > summary{cursor:pointer;color:var(--muted);font-size:12px;}\n"
    @"    details.raw > pre{margin-top:8px;}\n"
    @"  </style>\n";

  static NSString *const kOnDeviceAgentPageBody =
    @"</head>\n"
    @"<body>\n"
    @"  <div class=\"container\">\n"
	    @"    <h2 data-i18n=\"h_title\">iOS WDA On‑Device Agent (WDA Runner)</h2>\n"
		    @"    <div class=\"muted\">\n"
		    @"      <div data-i18n-html=\"intro_1\">This page configures and starts an agent running <b>inside</b> WebDriverAgentRunner (XCTest).</div>\n"
		    @"      <div data-i18n-html=\"intro_2\">If LAN access fails, try opening this page with <code>http://127.0.0.1:8100/agent</code> on the iPhone.</div>\n"
		    @"      <div data-i18n-html=\"wireless_hint_short\">Tip: If LAN access is unreachable, enable Runner <b>Wireless Data</b> in iPhone Settings, then reopen Runner.</div>\n"
		    @"    </div>\n"
        @"    <h3 data-i18n=\"h_access\">Access</h3>\n"
        @"    <div class=\"callout\">\n"
        @"      <div class=\"callout-row\">\n"
        @"        <div class=\"callout-text\" data-i18n-html=\"help_agent_token\">Agent Token protects <code>/agent/*</code> over Wi‑Fi/LAN. Rotate it to invalidate existing sessions.</div>\n"
        @"        <button type=\"button\" class=\"ghost callout-btn\" onclick=\"rotateToken()\" data-i18n=\"btn_rotate_token\">Rotate token</button>\n"
        @"      </div>\n"
        @"      <div id=\"rotate_token_row\" style=\"display:none;margin-top:10px\">\n"
        @"        <label style=\"margin-top:0\" data-i18n=\"label_new_token\">New token</label>\n"
        @"        <div style=\"display:flex;gap:8px;align-items:center;flex-wrap:wrap;\">\n"
        @"          <input id=\"rotate_token_value\" class=\"mono\" readonly style=\"flex:1 1 240px;\" />\n"
        @"          <button type=\"button\" class=\"ghost btn-sm\" onclick=\"copyRotatedToken()\" data-i18n=\"btn_copy\">Copy</button>\n"
        @"        </div>\n"
        @"        <div class=\"muted\" style=\"margin-top:6px\" data-i18n=\"help_new_token\">Keep this token secret. Anyone with it can access /agent/* over LAN.</div>\n"
        @"      </div>\n"
        @"    </div>\n"
	    @"    <label data-i18n=\"label_base_url\">Base URL (OpenAI-compatible)</label>\n"
    @"    <input id=\"base_url\" class=\"mono\" placeholder=\"https://...\" autocapitalize=\"none\" autocorrect=\"off\" spellcheck=\"false\" />\n"
    @"    <label data-i18n=\"label_model\">Model</label>\n"
    @"    <input id=\"model\" class=\"mono\" placeholder=\"gpt-4o-mini / ...\" autocapitalize=\"none\" autocorrect=\"off\" spellcheck=\"false\" />\n"
    @"    <label data-i18n=\"label_api_mode\">API Mode</label>\n"
    @"    <select id=\"api_mode\" class=\"ghost\" style=\"width:100%;min-height:44px;padding:10px 12px;border-radius:var(--radius);\">\n"
    @"      <option value=\"responses\" data-i18n=\"opt_responses\">Responses</option>\n"
    @"      <option value=\"chat_completions\" data-i18n=\"opt_chat_completions\">Chat Completions</option>\n"
    @"    </select>\n"
    @"    <div id=\"doubao_seed_cache_row\" style=\"display:none\">\n"
    @"      <label class=\"check muted\"><input type=\"checkbox\" id=\"doubao_seed_enable_session_cache\" checked /> <span data-i18n=\"cb_doubao_cache\">Enable Session Cache (Doubao Seed)</span></label>\n"
    @"    </div>\n"
    @"    <label data-i18n=\"label_api_key\">API Key</label>\n"
    @"    <input id=\"api_key\" class=\"mono\" type=\"password\" placeholder=\"sk-...\" autocapitalize=\"none\" autocorrect=\"off\" spellcheck=\"false\" autocomplete=\"off\" />\n"
    @"    <label class=\"check muted\"><input type=\"checkbox\" id=\"show_api_key\" /> <span data-i18n=\"cb_show_api_key\">Show API key</span></label>\n"
    @"    <label class=\"check muted\"><input type=\"checkbox\" id=\"remember_api_key\" /> <span data-i18n=\"cb_remember_api_key\">Remember API key on device (NOT recommended for shared devices)</span></label>\n"
    @"    <div class=\"label-row\">\n"
    @"      <label for=\"task\" data-i18n=\"label_task\">Task</label>\n"
    @"      <div class=\"label-actions\">\n"
    @"        <button type=\"button\" class=\"ghost btn-sm\" onclick=\"openEditorPage('task')\" data-i18n=\"btn_edit_page\">Edit Page</button>\n"
    @"      </div>\n"
    @"    </div>\n"
    @"    <textarea id=\"task\" placeholder=\"Describe what to do... (e.g., open Xiaohongshu and ...)\" data-i18n-placeholder=\"ph_task\"></textarea>\n"
    @"    <div class=\"row\">\n"
    @"      <div>\n"
    @"        <label data-i18n=\"label_max_steps\">Max Steps (&gt;0)</label>\n"
    @"        <input id=\"max_steps\" placeholder=\"__DEFAULT_MAX_STEPS__\" inputmode=\"numeric\" />\n"
    @"      </div>\n"
    @"      <div>\n"
    @"        <label data-i18n=\"label_timeout\">Timeout (seconds, &gt;0)</label>\n"
    @"        <input id=\"timeout_seconds\" placeholder=\"__DEFAULT_TIMEOUT_SECONDS__\" inputmode=\"numeric\" />\n"
    @"      </div>\n"
    @"      <div>\n"
    @"        <label data-i18n=\"label_step_delay\">Step Delay (seconds, &gt;0)</label>\n"
    @"        <input id=\"step_delay_seconds\" placeholder=\"__DEFAULT_STEP_DELAY_SECONDS__\" inputmode=\"decimal\" />\n"
    @"      </div>\n"
    @"    </div>\n"
    @"    <label id=\"max_tokens_label\">Max Completion Tokens (&gt;0)</label>\n"
    @"    <input id=\"max_completion_tokens\" placeholder=\"__DEFAULT_MAX_COMPLETION_TOKENS__\" inputmode=\"numeric\" />\n"
    @"    <label data-i18n=\"label_reasoning_effort\">Reasoning Effort</label>\n"
    @"    <input id=\"reasoning_effort\" class=\"mono\" placeholder=\"(default) e.g. minimal / low / medium / high\" data-i18n-placeholder=\"ph_reasoning_effort\" autocapitalize=\"none\" autocorrect=\"off\" spellcheck=\"false\" />\n"
    @"    <h3 data-i18n=\"h_system_prompt\">System Prompt</h3>\n"
    @"    <div class=\"muted\">\n"
    @"      <div data-i18n=\"help_system_prompt\">Custom system prompt only takes effect when the checkbox is enabled. Date placeholders (replaced at runtime):</div>\n"
    @"      <div class=\"placeholder-grid\">\n"
    @"        <div><code>{{DATE_ZH}}</code></div><div class=\"ex\">-&gt; __DATE_ZH_EXAMPLE__</div>\n"
    @"        <div><code>{{DATE_EN}}</code></div><div class=\"ex\">-&gt; __DATE_EN_EXAMPLE__</div>\n"
    @"      </div>\n"
    @"    </div>\n"
    @"    <div class=\"label-row\" style=\"margin-top:10px\">\n"
    @"      <label class=\"check muted\"><input type=\"checkbox\" id=\"use_custom_system_prompt\" /> <span data-i18n=\"cb_use_custom_system_prompt\">Use custom system prompt</span></label>\n"
    @"      <div class=\"label-actions\">\n"
    @"        <button type=\"button\" class=\"ghost btn-sm\" onclick=\"restoreSystemPromptDefault()\" data-i18n=\"btn_restore_system_prompt\">Restore default template</button>\n"
    @"        <button type=\"button\" class=\"ghost btn-sm\" onclick=\"openEditorPage('system_prompt')\" data-i18n=\"btn_edit_page\">Edit Page</button>\n"
    @"      </div>\n"
    @"    </div>\n"
    @"    <textarea id=\"system_prompt\" class=\"mono\" placeholder=\"(default system prompt)\" data-i18n-placeholder=\"ph_system_prompt\"></textarea>\n"
    @"    <label class=\"check muted\"><input type=\"checkbox\" id=\"insecure_skip_tls_verify\" /> <span data-i18n=\"cb_insecure_skip_tls\">Insecure TLS (model requests only)</span></label>\n"
    @"    <label class=\"check muted\"><input type=\"checkbox\" id=\"half_res_screenshot\" /> <span data-i18n=\"cb_half_res_screenshot\">Half-resolution screenshots</span></label>\n"
    @"    <label class=\"check muted\"><input type=\"checkbox\" id=\"use_w3c_actions_for_swipe\" /> <span data-i18n=\"cb_use_w3c_actions_for_swipe\">Use W3C actions for swipe</span></label>\n"
    @"    <label class=\"check muted\"><input type=\"checkbox\" id=\"restart_responses_by_plan\" /> <span data-i18n=\"cb_restart_responses_by_plan\">Restart history when a plan item completes (Responses)</span></label>\n"
    @"    <label class=\"check muted\"><input type=\"checkbox\" id=\"debug_log_raw_assistant\" /> <span data-i18n=\"cb_debug_raw\">Debug raw conversation (sensitive fields redacted)</span></label>\n"
    @"    <div id=\"form_error\" class=\"error\" style=\"display:none\"></div>\n"
    @"    <div id=\"readiness\" class=\"chips\" style=\"display:none\"></div>\n"
    @"    <div id=\"readiness_detail\" class=\"muted readiness-detail\" style=\"display:none\"></div>\n"
    @"    <pre id=\"token_summary\" class=\"muted\" style=\"display:none\"></pre>\n"
    @"    <div class=\"actions\">\n"
    @"      <button id=\"btn_save\" class=\"primary\" onclick=\"saveCfg()\" data-i18n=\"btn_save\">Save</button>\n"
    @"      <button id=\"btn_start\" class=\"primary\" onclick=\"start()\" data-i18n=\"btn_start\">Start</button>\n"
    @"      <button id=\"btn_stop\" class=\"danger\" onclick=\"stop()\" data-i18n=\"btn_stop\">Stop</button>\n"
    @"      <button id=\"btn_reset\" class=\"ghost\" onclick=\"resetAll()\" data-i18n=\"btn_reset\">Reset</button>\n"
    @"    </div>\n"
    @"    <h3 data-i18n=\"h_status\">Status</h3>\n"
    @"    <pre id=\"status\">Loading...</pre>\n"
    @"    <h3 data-i18n=\"h_notes\">Notes</h3>\n"
    @"    <pre id=\"notes\"></pre>\n"
    @"    <h3 data-i18n=\"h_conversation\">Conversation</h3>\n"
    @"    <div class=\"muted\" style=\"display:flex;gap:10px;align-items:center;flex-wrap:wrap;\">\n"
    @"      <span data-i18n=\"label_view\">View:</span>\n"
    @"      <select id=\"chat_mode\" class=\"ghost\" style=\"flex:0 0 auto;min-height:38px;padding:6px 10px;border-radius:var(--radius);\">\n"
    @"        <option value=\"structured\" data-i18n=\"opt_structured\">Structured</option>\n"
    @"        <option value=\"raw\" data-i18n=\"opt_raw\">Raw (request/response)</option>\n"
    @"      </select>\n"
    @"      <label class=\"check muted\" style=\"margin-top:0\"><input type=\"checkbox\" id=\"chat_show_screenshots\" /> <span data-i18n=\"cb_show_screenshots\">Show screenshots</span></label>\n"
    @"      <span data-i18n=\"help_raw_view\">Raw shows per-turn API request/response JSON (history content omitted; images are placeholders).</span>\n"
    @"    </div>\n"
    @"    <div id=\"chat\" class=\"chat\"></div>\n"
    @"    <h3 data-i18n=\"h_logs\">Logs</h3>\n"
    @"    <div id=\"logs\" class=\"chat\"></div>\n"
    @"  </div>\n"
    @"  <script>\n";

  static NSString *const kOnDeviceAgentPageJS =
    @"    const DEFAULT_SYSTEM_PROMPT = __DEFAULT_SYSTEM_PROMPT_JSON__;\n"
    @"    const LANG = ((navigator.language || '').toLowerCase().startsWith('zh')) ? 'zh' : 'en';\n"
    @"    const I18N = {\n"
    @"      en: {\n"
    @"        page_title: 'iOS WDA On‑Device Agent',\n"
    @"        h_title: 'iOS WDA On‑Device Agent (WDA Runner)',\n"
    @"        intro_1: 'This page configures and starts an agent running <b>inside</b> WebDriverAgentRunner (XCTest).',\n"
    @"        intro_2: 'If LAN access fails, try opening this page with <code>http://127.0.0.1:8100/agent</code> on the iPhone.',\n"
    @"        wireless_hint_short: 'Tip: If LAN access is unreachable, enable Runner <b>Wireless Data</b> in iPhone Settings, then reopen Runner.',\n"
        @"        h_access: 'Access',\n"
        @"        help_agent_token: 'Agent Token protects <code>/agent/*</code> over Wi‑Fi/LAN. Rotate it to invalidate existing sessions.',\n"
        @"        btn_rotate_token: 'Rotate token',\n"
        @"        label_new_token: 'New token',\n"
        @"        help_new_token: 'Keep this token secret. Anyone with it can access /agent/* over LAN.',\n"
        @"        btn_copy: 'Copy',\n"
    @"        label_base_url: 'Base URL (OpenAI-compatible)',\n"
    @"        label_model: 'Model',\n"
        @"        label_api_mode: 'API Mode',\n"
        @"        opt_chat_completions: 'Chat Completions',\n"
        @"        opt_responses: 'Responses',\n"
        @"        cb_doubao_cache: 'Enable Session Cache (Doubao Seed)',\n"
    @"        label_api_key: 'API Key',\n"
    @"        cb_show_api_key: 'Show API key',\n"
    @"        cb_remember_api_key: 'Remember API key on device (NOT recommended for shared devices)',\n"
    @"        ph_api_key_set: '(set)',\n"
    @"        label_task: 'Task',\n"
    @"        btn_edit_page: 'Edit Page',\n"
    @"        ph_task: 'Describe what to do... (e.g., open Xiaohongshu and ...)',\n"
    @"        label_max_steps: 'Max Steps (>0)',\n"
    @"        label_timeout: 'Timeout (seconds, >0)',\n"
    @"        label_step_delay: 'Step Delay (seconds, >0)',\n"
    @"        label_max_output_tokens_gt0: 'Max Output Tokens (>0)',\n"
    @"        label_max_completion_tokens_gt0: 'Max Completion Tokens (>0)',\n"
    @"        label_max_output_tokens: 'Max Output Tokens',\n"
    @"        label_max_completion_tokens: 'Max Completion Tokens',\n"
    @"        label_reasoning_effort: 'Reasoning Effort',\n"
    @"        ph_reasoning_effort: '(default) e.g. minimal / low / medium / high',\n"
    @"        h_system_prompt: 'System Prompt',\n"
    @"        help_system_prompt: 'Custom system prompt only takes effect when the checkbox is enabled. Date placeholders (replaced at runtime):',\n"
    @"        cb_use_custom_system_prompt: 'Use custom system prompt',\n"
        @"        btn_restore_system_prompt: 'Restore default template',\n"
        @"        ph_system_prompt: '(default system prompt)',\n"
        @"        cb_insecure_skip_tls: 'Insecure TLS (model requests only; debug only; MITM risk)',\n"
        @"        cb_half_res_screenshot: 'Half-resolution screenshots',\n"
        @"        cb_use_w3c_actions_for_swipe: 'Use W3C actions for swipe',\n"
        @"        cb_restart_responses_by_plan: 'Restart history when a plan item completes (Responses)',\n"
        @"        cb_debug_raw: 'Debug raw conversation (OFF by default; API key / Authorization / image base64 are redacted)',\n"
    @"        btn_save: 'Save',\n"
    @"        btn_start: 'Start',\n"
    @"        btn_stop: 'Stop',\n"
    @"        btn_reset: 'Reset',\n"
    @"        h_status: 'Status',\n"
    @"        h_notes: 'Notes',\n"
    @"        h_conversation: 'Conversation',\n"
    @"        label_view: 'View:',\n"
    @"        opt_structured: 'Structured',\n"
    @"        opt_raw: 'Raw (request/response)',\n"
    @"        cb_show_screenshots: 'Show screenshots',\n"
    @"        help_raw_view: 'Raw shows per-turn API request/response JSON (history content omitted; images are placeholders).',\n"
    @"        h_logs: 'Logs',\n"
    @"        chip_runner_ok: 'Runner reachable',\n"
    @"        chip_runner_bad: 'Runner unreachable',\n"
    @"        chip_auth_ok: 'Auth OK',\n"
    @"        chip_auth_bad: 'LAN requires token',\n"
    @"        chip_config_ok: 'Config OK',\n"
    @"        chip_config_bad: 'Config incomplete',\n"
    @"        chip_key_ok: 'API key OK',\n"
    @"        chip_key_bad: 'API key missing',\n"
    @"        chip_running: 'Running',\n"
    @"        chip_stopped: 'Stopped',\n"
    @"        err_base_url_required: 'Base URL is required',\n"
    @"        err_model_required: 'Model is required',\n"
    @"        err_task_required: 'Task is required',\n"
    @"        err_api_key_required: 'API Key is required',\n"
    @"        err_agent_token_required: 'Agent Token is required for LAN access',\n"
    @"        err_unauthorized: 'Unauthorized (missing/invalid Agent Token)',\n"
    @"        err_network: 'Network error',\n"
    @"        err_max_steps_gt0: 'Max Steps must be > 0',\n"
    @"        err_timeout_gt0: 'Timeout (seconds) must be > 0',\n"
    @"        err_step_delay_gt0: 'Step Delay (seconds) must be > 0',\n"
    @"        err_must_be_gt0: 'must be > 0',\n"
    @"        word_step: 'Step',\n"
    @"        word_attempt: 'attempt',\n"
    @"        sep_reasoning: '--- reasoning ---',\n"
    @"        sep_content: '--- content ---',\n"
    @"        raw_disabled: '<raw capture disabled>',\n"
    @"      },\n"
    @"      zh: {\n"
    @"        page_title: 'iOS WDA 设备端智能体',\n"
    @"        h_title: 'iOS WDA 设备端智能体（WDA Runner）',\n"
    @"        intro_1: '此页面用于配置并启动一个运行在 <b>WebDriverAgentRunner (XCTest)</b> 内部的智能体。',\n"
    @"        intro_2: '如果局域网访问失败，请在 iPhone 上用 <code>http://127.0.0.1:8100/agent</code> 打开此页面。',\n"
    @"        wireless_hint_short: '提示：如果局域网不可达，请在 iPhone 设置中为 Runner 开启<b>无线数据</b>，然后重新打开 Runner。',\n"
        @"        h_access: '访问控制',\n"
        @"        help_agent_token: 'Agent Token 用于保护局域网中的 <code>/agent/*</code>。旋转 token 会使已存在的会话失效。',\n"
        @"        btn_rotate_token: '旋转 token',\n"
        @"        label_new_token: '新 token',\n"
        @"        help_new_token: '请妥善保管。任何人拿到它都可以在局域网中访问 /agent/*。',\n"
        @"        btn_copy: '复制',\n"
    @"        label_base_url: 'Base URL（OpenAI 兼容）',\n"
    @"        label_model: '模型',\n"
        @"        label_api_mode: 'API 模式',\n"
        @"        opt_chat_completions: 'Chat Completions',\n"
        @"        opt_responses: 'Responses',\n"
        @"        cb_doubao_cache: '启用会话缓存（豆包 Seed）',\n"
    @"        label_api_key: 'API Key',\n"
    @"        cb_show_api_key: '显示 API key',\n"
    @"        cb_remember_api_key: '在设备上记住 API key（不建议共享设备）',\n"
    @"        ph_api_key_set: '（已设置）',\n"
    @"        label_task: '任务',\n"
    @"        btn_edit_page: '编辑页',\n"
    @"        ph_task: '描述要做什么……（例如：打开小红书并……）',\n"
    @"        label_max_steps: '最大步数（>0）',\n"
    @"        label_timeout: '超时（秒，>0）',\n"
    @"        label_step_delay: '步间延迟（秒，>0）',\n"
    @"        label_max_output_tokens_gt0: '最大输出 tokens（>0）',\n"
    @"        label_max_completion_tokens_gt0: '最大 completion tokens（>0）',\n"
    @"        label_max_output_tokens: '最大输出 tokens',\n"
    @"        label_max_completion_tokens: '最大 completion tokens',\n"
    @"        label_reasoning_effort: '思考强度',\n"
    @"        ph_reasoning_effort: '（默认）例如：minimal / low / medium / high',\n"
    @"        h_system_prompt: '系统提示词',\n"
    @"        help_system_prompt: '自定义系统提示词仅在勾选后生效。日期占位符（运行时替换）：',\n"
    @"        cb_use_custom_system_prompt: '使用自定义系统提示词',\n"
        @"        btn_restore_system_prompt: '恢复默认模板',\n"
        @"        ph_system_prompt: '（默认系统提示词）',\n"
        @"        cb_insecure_skip_tls: '不安全 TLS（仅模型请求；仅调试；有中间人风险）',\n"
        @"        cb_half_res_screenshot: '半分辨率截图',\n"
        @"        cb_use_w3c_actions_for_swipe: 'Swipe 使用 W3C actions',\n"
        @"        cb_restart_responses_by_plan: '计划项完成后重启对话历史（Responses）',\n"
        @"        cb_debug_raw: '调试：记录原始对话（默认关闭；API key / Authorization / 图片 base64 会脱敏）',\n"
    @"        btn_save: '保存',\n"
    @"        btn_start: '开始',\n"
    @"        btn_stop: '停止',\n"
    @"        btn_reset: '重置',\n"
    @"        h_status: '状态',\n"
    @"        h_notes: '备注',\n"
    @"        h_conversation: '对话',\n"
    @"        label_view: '视图：',\n"
    @"        opt_structured: '结构化',\n"
    @"        opt_raw: '原始（请求/响应）',\n"
    @"        cb_show_screenshots: '显示截图',\n"
    @"        help_raw_view: '原始视图显示每轮 API 请求/响应 JSON（历史内容省略；图片会用占位符）。',\n"
    @"        h_logs: '日志',\n"
    @"        chip_runner_ok: 'Runner 可达',\n"
    @"        chip_runner_bad: 'Runner 不可达',\n"
    @"        chip_auth_ok: '已授权',\n"
    @"        chip_auth_bad: '局域网需要 token',\n"
    @"        chip_config_ok: '配置就绪',\n"
    @"        chip_config_bad: '配置未完成',\n"
    @"        chip_key_ok: '密钥就绪',\n"
    @"        chip_key_bad: '缺少密钥',\n"
    @"        chip_running: '运行中',\n"
    @"        chip_stopped: '未运行',\n"
    @"        err_base_url_required: 'Base URL 必填',\n"
    @"        err_model_required: '模型必填',\n"
    @"        err_task_required: '任务必填',\n"
    @"        err_api_key_required: 'API 密钥必填',\n"
    @"        err_agent_token_required: '局域网访问需要 Agent Token',\n"
    @"        err_unauthorized: '未授权（Agent Token 缺失或无效）',\n"
    @"        err_network: '网络错误',\n"
    @"        err_max_steps_gt0: '最大步数必须 > 0',\n"
    @"        err_timeout_gt0: '超时（秒）必须 > 0',\n"
    @"        err_step_delay_gt0: '步间延迟（秒）必须 > 0',\n"
    @"        err_must_be_gt0: '必须 > 0',\n"
    @"        word_step: '步骤',\n"
    @"        word_attempt: '尝试',\n"
    @"        sep_reasoning: '--- 思考 ---',\n"
    @"        sep_content: '--- 内容 ---',\n"
    @"        raw_disabled: '<未开启 raw 记录>',\n"
    @"      }\n"
    @"    };\n"
    @"    function t(key){\n"
    @"      const table = I18N[LANG] || I18N.en;\n"
    @"      return (table && table[key]) ? table[key] : ((I18N.en && I18N.en[key]) ? I18N.en[key] : key);\n"
    @"    }\n"
    @"    function applyI18n(){\n"
    @"      try { document.title = t('page_title'); } catch (e) {}\n"
    @"      const nodes = document.querySelectorAll('[data-i18n]');\n"
    @"      for (const el of nodes) {\n"
    @"        const key = el.getAttribute('data-i18n') || '';\n"
    @"        if (!key) continue;\n"
    @"        el.textContent = t(key);\n"
    @"      }\n"
    @"      const ph = document.querySelectorAll('[data-i18n-placeholder]');\n"
    @"      for (const el of ph) {\n"
    @"        const key = el.getAttribute('data-i18n-placeholder') || '';\n"
    @"        if (!key) continue;\n"
    @"        el.placeholder = t(key);\n"
    @"      }\n"
    @"      const html = document.querySelectorAll('[data-i18n-html]');\n"
    @"      for (const el of html) {\n"
    @"        const key = el.getAttribute('data-i18n-html') || '';\n"
    @"        if (!key) continue;\n"
    @"        el.innerHTML = t(key);\n"
    @"      }\n"
    @"    }\n"
    @"    let dirty = false;\n"
    @"    let lastChatItems = [];\n"
    @"    let lastLogLines = [];\n"
    @"    let lastStatus = null;\n"
    @"    let lastStatusError = '';\n"
    @"    let lastStatusCode = 0;\n"
    @"    let lastRunnerOk = false;\n"
    @"    let lastRunnerError = '';\n"
    @"    let composing = false;\n"
    @"    const shotCache = {};\n"
    @"    const shotLoading = new Set();\n"
    @"    let events = null;\n"
    @"    let eventsReady = false;\n"
    @"    let pollTimer = null;\n"
    @"    let pendingAutoRefresh = false;\n"
    @"    let lastTokenUsage = null;\n"
    @"    const MAX_LOG_LINES = 2000;\n"
    @"    function setInvalid(el, on){\n"
    @"      if (!el || !el.classList) return;\n"
    @"      if (on) el.classList.add('invalid'); else el.classList.remove('invalid');\n"
    @"    }\n"
    @"    function setFormError(lines){\n"
    @"      const el = document.getElementById('form_error');\n"
    @"      const arr = Array.isArray(lines) ? lines.filter(Boolean) : [];\n"
    @"      if (!el) {\n"
    @"        if (arr.length) alert(arr.join('\\n'));\n"
    @"        return;\n"
    @"      }\n"
    @"      if (!arr.length) {\n"
    @"        el.textContent = '';\n"
    @"        el.style.display = 'none';\n"
    @"        return;\n"
    @"      }\n"
    @"      el.textContent = arr.join('\\n');\n"
    @"      el.style.display = '';\n"
    @"    }\n"
    @"    function clearFormError(){\n"
    @"      setFormError([]);\n"
    @"      for (const id of ['base_url','model','api_key','task','max_steps','timeout_seconds','step_delay_seconds','max_completion_tokens']){\n"
    @"        const el = document.getElementById(id);\n"
    @"        if (el) el.classList.remove('invalid');\n"
    @"      }\n"
    @"    }\n"
    @"    function isEditing(){\n"
    @"      const el = document.activeElement;\n"
    @"      if (!el || !el.tagName) return false;\n"
    @"      const tag = el.tagName.toLowerCase();\n"
    @"      return tag === 'input' || tag === 'textarea';\n"
    @"    }\n"
    @"    function markDirty(){ dirty = true; clearFormError(); updateReadinessUI(); }\n"
    @"    function initDirtyTracking(){\n"
    @"      const ids = ['base_url','model','api_mode','api_key','task','max_steps','max_completion_tokens','reasoning_effort','timeout_seconds','step_delay_seconds','system_prompt'];\n"
    @"      for (const id of ids){\n"
    @"        const el = document.getElementById(id);\n"
    @"        if (!el) continue;\n"
    @"        el.addEventListener('input', markDirty);\n"
    @"        el.addEventListener('change', markDirty);\n"
    @"        if (id === 'model') {\n"
    @"          el.addEventListener('input', updateApiModeUI);\n"
    @"          el.addEventListener('change', updateApiModeUI);\n"
    @"        }\n"
    @"        el.addEventListener('compositionstart', () => { composing = true; });\n"
    @"        el.addEventListener('compositionend', () => { composing = false; markDirty(); });\n"
    @"      }\n"
    @"      const cbs = ['remember_api_key','insecure_skip_tls_verify','half_res_screenshot','use_w3c_actions_for_swipe','restart_responses_by_plan','debug_log_raw_assistant','use_custom_system_prompt','doubao_seed_enable_session_cache'];\n"
    @"      for (const id of cbs){\n"
    @"        const el = document.getElementById(id);\n"
    @"        if (!el) continue;\n"
    @"        el.addEventListener('change', markDirty);\n"
    @"      }\n"
    @"      const show = document.getElementById('show_api_key');\n"
    @"      if (show) {\n"
    @"        show.addEventListener('change', () => {\n"
    @"          const keyEl = document.getElementById('api_key');\n"
    @"          if (!keyEl) return;\n"
    @"          keyEl.type = show.checked ? 'text' : 'password';\n"
    @"        });\n"
    @"      }\n"
    @"      const mode = document.getElementById('api_mode');\n"
    @"      if (mode) {\n"
    @"        mode.addEventListener('change', updateApiModeUI);\n"
    @"      }\n"
    @"    }\n"
    @"    async function commitIME(){\n"
    @"      // iOS Safari IME (e.g. Chinese) may not commit the last composed character before click handlers read input.value.\n"
    @"      if (isEditing() && document.activeElement) {\n"
    @"        try { document.activeElement.blur(); } catch (e) {}\n"
    @"        await new Promise(r => setTimeout(r, 50));\n"
    @"      }\n"
    @"      if (composing) {\n"
    @"        await new Promise(r => setTimeout(r, 50));\n"
    @"      }\n"
    @"    }\n"
    @"    function stripTokenFromURL(){\n"
    @"      // Agent Token should never live in the URL longer than the initial page load.\n"
    @"      try {\n"
    @"        const qs = new URLSearchParams(window.location.search || '');\n"
    @"        if (!qs.has('token')) return;\n"
    @"        qs.delete('token');\n"
    @"        const next = window.location.pathname + (qs.toString() ? ('?' + qs.toString()) : '') + (window.location.hash || '');\n"
    @"        window.history.replaceState({}, '', next);\n"
    @"      } catch (e) {}\n"
    @"    }\n"
    @"    async function api(path, method, body){\n"
    @"      const opts = {method: method || 'GET', credentials: 'same-origin'};\n"
    @"      const headers = {};\n"
    @"      if (body) { headers['Content-Type'] = 'application/json'; opts.body = JSON.stringify(body); }\n"
    @"      if (Object.keys(headers).length > 0) { opts.headers = headers; }\n"
    @"      let r;\n"
    @"      try {\n"
    @"        r = await fetch(path, opts);\n"
    @"      } catch (e) {\n"
    @"        const msg = `${t('err_network')}: ${(e && e.message) ? e.message : String(e)}`;\n"
    @"        const err = new Error(msg);\n"
    @"        err.status = 0;\n"
    @"        throw err;\n"
    @"      }\n"
    @"      const j = await r.json().catch(() => ({}));\n"
    @"      if (!r.ok) {\n"
    @"        const msg = ((j.value && j.value.error) || j.error || `HTTP ${r.status}`);\n"
    @"        const err = new Error(msg);\n"
    @"        err.status = r.status;\n"
    @"        err.body = j;\n"
    @"        throw err;\n"
    @"      }\n"
    @"      return j.value || {};\n"
    @"    }\n"
    @"    async function rotateToken(){\n"
    @"      await commitIME();\n"
    @"      clearFormError();\n"
    @"      try {\n"
    @"        const r = await api('/agent/rotate_token','POST');\n"
    @"        const tok = (r.agent_token || '').toString();\n"
    @"        const row = document.getElementById('rotate_token_row');\n"
    @"        const val = document.getElementById('rotate_token_value');\n"
    @"        if (val) { val.value = tok; }\n"
    @"        if (row) { row.style.display = tok.length ? '' : 'none'; }\n"
    @"        await refresh();\n"
    @"      } catch (e) {\n"
    @"        setFormError([e && e.message ? e.message : String(e)]);\n"
    @"      }\n"
    @"    }\n"
    @"    async function copyRotatedToken(){\n"
    @"      const val = document.getElementById('rotate_token_value');\n"
    @"      const tok = val ? (val.value || '').toString() : '';\n"
    @"      if (!tok) return;\n"
    @"      try {\n"
    @"        if (navigator.clipboard && navigator.clipboard.writeText) {\n"
    @"          await navigator.clipboard.writeText(tok);\n"
    @"          return;\n"
    @"        }\n"
    @"      } catch (e) {}\n"
    @"      try {\n"
    @"        if (val) { val.focus(); val.select(); }\n"
    @"        document.execCommand('copy');\n"
    @"      } catch (e) {}\n"
    @"    }\n"
	    @"    function restoreSystemPromptDefault(){\n"
	    @"      const el = document.getElementById('system_prompt');\n"
	    @"      if (!el) return;\n"
	    @"      el.value = DEFAULT_SYSTEM_PROMPT;\n"
	    @"      markDirty();\n"
	    @"    }\n"
	    @"    function openEditorPage(targetId){\n"
    @"      const t = encodeURIComponent((targetId || '').toString());\n"
    @"      window.location.href = `/agent/edit?target=${t}`;\n"
    @"    }\n"
    @"    function cfgFromUI(){\n"
    @"      const cfg = {\n"
    @"        base_url: document.getElementById('base_url').value,\n"
    @"        model: document.getElementById('model').value,\n"
    @"        api_mode: document.getElementById('api_mode').value,\n"
    @"        use_custom_system_prompt: document.getElementById('use_custom_system_prompt').checked,\n"
    @"        system_prompt: document.getElementById('system_prompt').value,\n"
    @"        remember_api_key: document.getElementById('remember_api_key').checked,\n"
    @"        debug_log_raw_assistant: document.getElementById('debug_log_raw_assistant').checked,\n"
    @"        doubao_seed_enable_session_cache: document.getElementById('doubao_seed_enable_session_cache').checked,\n"
    @"        half_res_screenshot: document.getElementById('half_res_screenshot').checked,\n"
    @"        use_w3c_actions_for_swipe: document.getElementById('use_w3c_actions_for_swipe').checked,\n"
    @"        restart_responses_by_plan: document.getElementById('restart_responses_by_plan').checked,\n"
    @"        task: document.getElementById('task').value,\n"
    @"        max_steps: document.getElementById('max_steps').value,\n"
    @"        max_completion_tokens: document.getElementById('max_completion_tokens').value,\n"
    @"        reasoning_effort: document.getElementById('reasoning_effort').value,\n"
    @"        timeout_seconds: document.getElementById('timeout_seconds').value,\n"
    @"        step_delay_seconds: document.getElementById('step_delay_seconds').value,\n"
    @"        insecure_skip_tls_verify: document.getElementById('insecure_skip_tls_verify').checked,\n"
    @"      };\n"
    @"      const key = (document.getElementById('api_key').value || '').trim();\n"
    @"      if (key.length > 0) { cfg.api_key = key; }\n"
    @"      return cfg;\n"
    @"    }\n"
    @"    function isStrictIntegerString(raw){\n"
    @"      return /^[+-]?\\d+$/.test(raw);\n"
    @"    }\n"
    @"    function isStrictNumberString(raw){\n"
    @"      return /^[+-]?(?:\\d+\\.?\\d*|\\.\\d+)(?:[eE][+-]?\\d+)?$/.test(raw);\n"
    @"    }\n"
    @"    function isLoopbackHost(){\n"
    @"      const h = ((window.location && window.location.hostname) ? window.location.hostname : '').toString().toLowerCase();\n"
    @"      return h === '127.0.0.1' || h === 'localhost' || h === '::1';\n"
    @"    }\n"
    @"    function computeStartValidation(){\n"
    @"      const errors = [];\n"
    @"      const invalid = {};\n"
    @"\n"
    @"      const baseUrlEl = document.getElementById('base_url');\n"
    @"      const modelEl = document.getElementById('model');\n"
    @"      const taskEl = document.getElementById('task');\n"
    @"      const apiKeyEl = document.getElementById('api_key');\n"
    @"      const maxStepsEl = document.getElementById('max_steps');\n"
    @"      const timeoutEl = document.getElementById('timeout_seconds');\n"
    @"      const delayEl = document.getElementById('step_delay_seconds');\n"
    @"      const tokensEl = document.getElementById('max_completion_tokens');\n"
    @"      const modeEl = document.getElementById('api_mode');\n"
    @"      const mode = modeEl ? (modeEl.value || 'responses') : 'responses';\n"
    @"      const tokenLabel = (mode === 'responses') ? t('label_max_output_tokens') : t('label_max_completion_tokens');\n"
    @"\n"
    @"      const baseUrl = ((baseUrlEl && baseUrlEl.value) || '').trim();\n"
    @"      if (!baseUrl.length) {\n"
    @"        invalid.base_url = true;\n"
    @"        errors.push(t('err_base_url_required'));\n"
    @"      }\n"
    @"      const model = ((modelEl && modelEl.value) || '').trim();\n"
    @"      if (!model.length) {\n"
    @"        invalid.model = true;\n"
    @"        errors.push(t('err_model_required'));\n"
    @"      }\n"
    @"      const task = ((taskEl && taskEl.value) || '').trim();\n"
    @"      if (!task.length) {\n"
    @"        invalid.task = true;\n"
    @"        errors.push(t('err_task_required'));\n"
    @"      }\n"
    @"\n"
    @"      const apiKey = ((apiKeyEl && apiKeyEl.value) || '').trim();\n"
    @"      const apiKeySet = !!(lastStatus && lastStatus.config && lastStatus.config.api_key_set);\n"
    @"      if (!apiKey.length && !apiKeySet) {\n"
    @"        invalid.api_key = true;\n"
    @"        errors.push(t('err_api_key_required'));\n"
    @"      }\n"
    @"\n"
    @"      if (!lastRunnerOk && lastRunnerError) {\n"
    @"        errors.push(`${t('chip_runner_bad')}: ${lastRunnerError}`);\n"
    @"      }\n"
    @"\n"
    @"      if (!isLoopbackHost() && lastStatusCode === 401) {\n"
    @"        errors.push(`${t('err_agent_token_required')}\\n${t('err_unauthorized')}`);\n"
    @"      } else if (!lastStatus && lastStatusError && lastStatusCode !== 0) {\n"
    @"        // When the Runner is alive but /agent/* is blocked, surface the reason.\n"
    @"        errors.push(lastStatusError);\n"
    @"      }\n"
    @"\n"
    @"      const maxStepsRaw = ((maxStepsEl && maxStepsEl.value) || '').trim();\n"
    @"      let maxStepsBad = false;\n"
    @"      if (maxStepsRaw.length) {\n"
    @"        const maxSteps = Number(maxStepsRaw);\n"
    @"        maxStepsBad = !(isStrictIntegerString(maxStepsRaw) && Number.isFinite(maxSteps) && maxSteps > 0);\n"
    @"      }\n"
    @"      invalid.max_steps = maxStepsBad;\n"
    @"      if (maxStepsBad) errors.push(t('err_max_steps_gt0'));\n"
    @"\n"
    @"      const timeoutRaw = ((timeoutEl && timeoutEl.value) || '').trim();\n"
    @"      let timeoutBad = false;\n"
    @"      if (timeoutRaw.length) {\n"
    @"        const timeout = Number(timeoutRaw);\n"
    @"        timeoutBad = !(isStrictNumberString(timeoutRaw) && Number.isFinite(timeout) && timeout > 0);\n"
    @"      }\n"
    @"      invalid.timeout_seconds = timeoutBad;\n"
    @"      if (timeoutBad) errors.push(t('err_timeout_gt0'));\n"
    @"\n"
    @"      const delayRaw = ((delayEl && delayEl.value) || '').trim();\n"
    @"      let delayBad = false;\n"
    @"      if (delayRaw.length) {\n"
    @"        const delay = Number(delayRaw);\n"
    @"        delayBad = !(isStrictNumberString(delayRaw) && Number.isFinite(delay) && delay > 0);\n"
    @"      }\n"
    @"      invalid.step_delay_seconds = delayBad;\n"
    @"      if (delayBad) errors.push(t('err_step_delay_gt0'));\n"
    @"\n"
    @"      const tokensRaw = ((tokensEl && tokensEl.value) || '').trim();\n"
    @"      let tokensBad = false;\n"
    @"      if (tokensRaw.length) {\n"
    @"        const tokens = Number(tokensRaw);\n"
    @"        tokensBad = !(isStrictIntegerString(tokensRaw) && Number.isFinite(tokens) && tokens > 0);\n"
    @"      }\n"
    @"      invalid.max_completion_tokens = tokensBad;\n"
    @"      if (tokensBad) errors.push(`${tokenLabel} ${t('err_must_be_gt0')}`);\n"
    @"\n"
    @"      return {errors, invalid};\n"
    @"    }\n"
    @"    function applyStartValidationInvalid(invalid){\n"
    @"      const ids = ['base_url','model','task','api_key','max_steps','timeout_seconds','step_delay_seconds','max_completion_tokens'];\n"
    @"      for (const id of ids) {\n"
    @"        const el = document.getElementById(id);\n"
    @"        setInvalid(el, !!(invalid && invalid[id]));\n"
    @"      }\n"
    @"    }\n"
    @"    function tokenUsageFromStatus(){\n"
    @"      if (!lastStatus) return null;\n"
    @"      const u = lastStatus.token_usage || lastStatus.tokenUsage || null;\n"
    @"      if (!u) return null;\n"
    @"      const req = Number(u.requests || u.req || 0);\n"
    @"      const input = Number(u.input_tokens || u.inputTokens || 0);\n"
    @"      const output = Number(u.output_tokens || u.outputTokens || 0);\n"
    @"      const cached = Number(u.cached_tokens || u.cachedTokens || 0);\n"
    @"      const total = Number(u.total_tokens || u.totalTokens || 0);\n"
    @"      return {requests:req, input, output, cached, total};\n"
    @"    }\n"
    @"    function updateTokenSummary(){\n"
    @"      const el = document.getElementById('token_summary');\n"
    @"      if (!el) return;\n"
    @"      const u = lastTokenUsage || tokenUsageFromStatus();\n"
    @"      if (!u || (!u.requests && !u.total && !u.input && !u.output && !u.cached)) {\n"
    @"        el.textContent = '';\n"
    @"        el.style.display = 'none';\n"
    @"        return;\n"
    @"      }\n"
    @"      const summary = (LANG === 'zh')\n"
    @"        ? `Token：请求 ${u.requests} · 输入 ${u.input} · 输出 ${u.output} · 缓存 ${u.cached} · 总计 ${u.total}`\n"
    @"        : `Tokens: req ${u.requests} · in ${u.input} · out ${u.output} · cached ${u.cached} · total ${u.total}`;\n"
    @"      let cacheLine = '';\n"
    @"      try {\n"
    @"        const cfg = (lastStatus && lastStatus.config) ? lastStatus.config : {};\n"
    @"        const enabled = !!(cfg && cfg.doubao_seed_enable_session_cache);\n"
    @"        const apiMode = (cfg.api_mode || '').toString();\n"
    @"        if (apiMode === 'responses') {\n"
    @"          const hit = (u.cached || 0) > 0;\n"
    @"          cacheLine = (LANG === 'zh')\n"
    @"            ? `缓存：${enabled ? '已开启' : '未开启'}${hit ? '（已命中）' : ''}`\n"
    @"            : `Cache: ${enabled ? 'enabled' : 'disabled'}${hit ? ' (hit)' : ''}`;\n"
    @"        }\n"
    @"      } catch (e) {}\n"
    @"      el.textContent = cacheLine ? (summary + '\\n' + cacheLine) : summary;\n"
    @"      el.style.display = '';\n"
    @"    }\n"
    @"    function updateReadinessUI(){\n"
    @"      const chipsEl = document.getElementById('readiness');\n"
    @"      const detailEl = document.getElementById('readiness_detail');\n"
    @"      const tokenEl = document.getElementById('token_summary');\n"
    @"      const startBtn = document.getElementById('btn_start');\n"
    @"      const stopBtn = document.getElementById('btn_stop');\n"
    @"      const saveBtn = document.getElementById('btn_save');\n"
    @"      const running = !!(lastStatus && lastStatus.running);\n"
    @"\n"
    @"      if (stopBtn) stopBtn.disabled = !running;\n"
    @"      if (saveBtn) saveBtn.disabled = running;\n"
    @"\n"
    @"      const v = computeStartValidation();\n"
    @"      const canStart = !running && v.errors.length === 0;\n"
    @"      if (startBtn) startBtn.disabled = !canStart;\n"
    @"\n"
    @"      if (chipsEl) {\n"
    @"        const chips = [];\n"
    @"        if (lastRunnerOk) {\n"
    @"          chips.push({text: t('chip_runner_ok'), ok: true});\n"
    @"        } else {\n"
    @"          chips.push({text: t('chip_runner_bad'), ok: false});\n"
    @"        }\n"
    @"        if (!isLoopbackHost()) {\n"
    @"          if (lastStatusCode === 401) chips.push({text: t('chip_auth_bad'), ok: false});\n"
    @"          else if (lastStatus) chips.push({text: t('chip_auth_ok'), ok: true});\n"
    @"        }\n"
    @"        const configOk = !v.invalid.base_url && !v.invalid.model && !v.invalid.task && !v.invalid.max_steps && !v.invalid.timeout_seconds && !v.invalid.step_delay_seconds && !v.invalid.max_completion_tokens;\n"
    @"        chips.push({text: configOk ? t('chip_config_ok') : t('chip_config_bad'), ok: configOk});\n"
    @"        const keyOk = !v.invalid.api_key;\n"
    @"        chips.push({text: keyOk ? t('chip_key_ok') : t('chip_key_bad'), ok: keyOk});\n"
    @"        chips.push({text: running ? t('chip_running') : t('chip_stopped'), ok: running});\n"
    @"\n"
    @"        chipsEl.innerHTML = '';\n"
    @"        for (const c of chips) {\n"
    @"          const s = document.createElement('span');\n"
    @"          s.className = 'chip ' + (c.ok ? 'ok' : 'bad');\n"
    @"          s.textContent = c.text;\n"
    @"          chipsEl.appendChild(s);\n"
    @"        }\n"
    @"        chipsEl.style.display = '';\n"
    @"      }\n"
    @"\n"
    @"      if (detailEl) {\n"
    @"        const lines = [];\n"
    @"        if (running) {\n"
    @"          lines.push((LANG === 'zh') ? '运行中：停止后可修改配置或重新开始。' : 'Running: stop to edit config or restart.');\n"
    @"        }\n"
    @"        if (!canStart && v.errors.length) {\n"
    @"          for (const x of v.errors) lines.push(x);\n"
    @"        }\n"
    @"        if (lines.length) {\n"
    @"          detailEl.textContent = lines.join('\\n');\n"
    @"          detailEl.style.display = '';\n"
    @"        } else {\n"
    @"          detailEl.textContent = '';\n"
    @"          detailEl.style.display = 'none';\n"
    @"        }\n"
    @"      }\n"
    @"      if (tokenEl) updateTokenSummary();\n"
    @"    }\n"
    @"    function validateBeforeStart(){\n"
    @"      const v = computeStartValidation();\n"
    @"      applyStartValidationInvalid(v.invalid);\n"
    @"      setFormError(v.errors);\n"
    @"      updateReadinessUI();\n"
    @"      return v.errors.length === 0;\n"
    @"    }\n"
    @"    function fillUI(cfg){\n"
    @"      document.getElementById('base_url').value = cfg.base_url || '';\n"
    @"      document.getElementById('model').value = cfg.model || '';\n"
    @"      document.getElementById('api_mode').value = cfg.api_mode || 'responses';\n"
    @"      document.getElementById('task').value = cfg.task || '';\n"
    @"      document.getElementById('max_steps').value = cfg.max_steps || __DEFAULT_MAX_STEPS__;\n"
    @"      document.getElementById('max_completion_tokens').value = cfg.max_completion_tokens || __DEFAULT_MAX_COMPLETION_TOKENS__;\n"
    @"      document.getElementById('reasoning_effort').value = cfg.reasoning_effort || '';\n"
    @"      document.getElementById('timeout_seconds').value = cfg.timeout_seconds || __DEFAULT_TIMEOUT_SECONDS__;\n"
    @"      document.getElementById('step_delay_seconds').value = cfg.step_delay_seconds || __DEFAULT_STEP_DELAY_SECONDS__;\n"
    @"      document.getElementById('use_custom_system_prompt').checked = !!cfg.use_custom_system_prompt;\n"
    @"      const sp = (cfg.system_prompt || '').toString();\n"
    @"      document.getElementById('system_prompt').value = sp.length ? sp : DEFAULT_SYSTEM_PROMPT;\n"
    @"      document.getElementById('remember_api_key').checked = !!cfg.remember_api_key;\n"
    @"      document.getElementById('doubao_seed_enable_session_cache').checked = (cfg.doubao_seed_enable_session_cache !== false);\n"
    @"      document.getElementById('insecure_skip_tls_verify').checked = !!cfg.insecure_skip_tls_verify;\n"
    @"      document.getElementById('half_res_screenshot').checked = !!cfg.half_res_screenshot;\n"
    @"      document.getElementById('use_w3c_actions_for_swipe').checked = (cfg.use_w3c_actions_for_swipe !== false);\n"
    @"      document.getElementById('restart_responses_by_plan').checked = !!cfg.restart_responses_by_plan;\n"
    @"      document.getElementById('debug_log_raw_assistant').checked = !!cfg.debug_log_raw_assistant;\n"
    @"      if (cfg.api_key_set) {\n"
    @"        document.getElementById('api_key').placeholder = t('ph_api_key_set');\n"
    @"      }\n"
    @"      updateApiModeUI();\n"
    @"    }\n"
    @"    function updateApiModeUI(){\n"
    @"      const modeEl = document.getElementById('api_mode');\n"
    @"      const mode = modeEl ? (modeEl.value || 'responses') : 'responses';\n"
    @"      const label = document.getElementById('max_tokens_label');\n"
    @"      if (!label) return;\n"
    @"      label.textContent = (mode === 'responses') ? t('label_max_output_tokens_gt0') : t('label_max_completion_tokens_gt0');\n"
    @"      const cacheRow = document.getElementById('doubao_seed_cache_row');\n"
    @"      const modelEl = document.getElementById('model');\n"
    @"      const model = modelEl ? ((modelEl.value || '').toString().trim().toLowerCase()) : '';\n"
    @"      if (cacheRow) {\n"
    @"        const show = (mode === 'responses') && model.startsWith('doubao-seed');\n"
    @"        cacheRow.style.display = show ? '' : 'none';\n"
    @"      }\n"
    @"    }\n"
    @"    function clearNode(el){\n"
    @"      if (!el) return;\n"
    @"      while (el.firstChild) el.removeChild(el.firstChild);\n"
    @"    }\n"
    @"    function prettyRaw(raw){\n"
    @"      const s = (raw || '').toString();\n"
    @"      const t0 = s.trim();\n"
    @"      if (!t0) return '';\n"
    @"      if ((t0.startsWith('{') && t0.endsWith('}')) || (t0.startsWith('[') && t0.endsWith(']'))) {\n"
    @"        try { return JSON.stringify(JSON.parse(t0), null, 2); } catch (e) {}\n"
    @"      }\n"
    @"      return s;\n"
    @"    }\n"
    @"    function screenshotPlaceholderText(){\n"
    @"      return (LANG === 'zh') ? '正在加载截图…' : 'Loading screenshot…';\n"
    @"    }\n"
    @"    function screenshotNotFoundText(){\n"
    @"      return (LANG === 'zh') ? '未找到截图' : 'Screenshot not found';\n"
    @"    }\n"
    @"    function rawJSONLabel(){\n"
    @"      return (LANG === 'zh') ? '原始 JSON' : 'Raw JSON';\n"
    @"    }\n"
    @"    function otherLogsLabel(){\n"
    @"      return (LANG === 'zh') ? '其它' : 'Other';\n"
    @"    }\n"
    @"    async function ensureStepScreenshot(step, imgEl, placeholderEl){\n"
    @"      if (!imgEl) return;\n"
    @"      const key = String(step);\n"
    @"      if (shotCache[key]) {\n"
    @"        imgEl.src = 'data:image/png;base64,' + shotCache[key];\n"
    @"        imgEl.style.display = 'block';\n"
    @"        if (placeholderEl) placeholderEl.style.display = 'none';\n"
    @"        return;\n"
    @"      }\n"
    @"      if (shotLoading.has(key)) return;\n"
    @"      shotLoading.add(key);\n"
    @"      if (placeholderEl) {\n"
    @"        placeholderEl.textContent = screenshotPlaceholderText();\n"
    @"        placeholderEl.style.display = '';\n"
    @"      }\n"
    @"      try {\n"
    @"        const r = await api('/agent/step_screenshot?step=' + encodeURIComponent(step));\n"
    @"        const b64 = (r && r.png_base64) ? r.png_base64 : '';\n"
    @"        if (r && r.ok && b64) {\n"
    @"          shotCache[key] = b64;\n"
    @"          imgEl.src = 'data:image/png;base64,' + b64;\n"
    @"          imgEl.style.display = 'block';\n"
    @"          if (placeholderEl) placeholderEl.style.display = 'none';\n"
    @"        } else {\n"
    @"          imgEl.style.display = 'none';\n"
    @"          if (placeholderEl) placeholderEl.textContent = (r && r.error) ? String(r.error) : screenshotNotFoundText();\n"
    @"        }\n"
    @"      } catch (e) {\n"
    @"        imgEl.style.display = 'none';\n"
    @"        if (placeholderEl) placeholderEl.textContent = (e && e.message) ? e.message : String(e);\n"
    @"      } finally {\n"
    @"        shotLoading.delete(key);\n"
    @"      }\n"
    @"    }\n"
    @"    function attemptCountLabel(n){\n"
    @"      if (!(Number.isFinite(n) && n > 1)) return '';\n"
    @"      return (LANG === 'zh') ? ` · ${n} 次尝试` : ` · ${n} attempts`;\n"
    @"    }\n"
    @"    function appendChatMsg(body, it, mode){\n"
    @"      if (!body || !it) return;\n"
    @"      const kind = (it.kind || '').toString();\n"
    @"      const attempt = (it.attempt != null) ? Number(it.attempt) : 0;\n"
    @"      const ts = (it.ts || '').toString();\n"
    @"\n"
    @"      const box = document.createElement('div');\n"
    @"      box.className = 'msg';\n"
    @"      const hdr = document.createElement('div');\n"
    @"      hdr.className = 'msg-hdr';\n"
    @"      const parts = [];\n"
    @"      if (ts) parts.push(ts);\n"
    @"      if (kind) parts.push(kind.toUpperCase());\n"
    @"      if (attempt > 0) parts.push(`${t('word_attempt')} ${attempt}`);\n"
    @"      hdr.textContent = parts.join(' · ');\n"
    @"      box.appendChild(hdr);\n"
    @"\n"
    @"      if (mode !== 'raw') {\n"
    @"        const pre = document.createElement('pre');\n"
    @"        if (kind === 'request') {\n"
    @"          pre.textContent = it.text || '';\n"
    @"        } else {\n"
    @"          let text = '';\n"
    @"          if (it.reasoning) {\n"
    @"            text += t('sep_reasoning') + '\\n' + it.reasoning + '\\n\\n';\n"
    @"          }\n"
    @"          text += t('sep_content') + '\\n' + (it.content || '');\n"
    @"          pre.textContent = text;\n"
    @"        }\n"
    @"        box.appendChild(pre);\n"
    @"      }\n"
    @"\n"
    @"      const rawDetails = document.createElement('details');\n"
    @"      rawDetails.className = 'raw';\n"
    @"      if (mode === 'raw') rawDetails.open = true;\n"
    @"      const sum = document.createElement('summary');\n"
    @"      sum.textContent = rawJSONLabel();\n"
    @"      rawDetails.appendChild(sum);\n"
    @"      const rawPre = document.createElement('pre');\n"
    @"      rawPre.textContent = prettyRaw(it.raw || '') || t('raw_disabled');\n"
    @"      rawDetails.appendChild(rawPre);\n"
    @"      box.appendChild(rawDetails);\n"
    @"\n"
    @"      body.appendChild(box);\n"
    @"    }\n"
    @"    function parseLogLine(line){\n"
    @"      const s = (line || '').toString().trim();\n"
    @"      let d = null;\n"
    @"      if (s.startsWith('{') && s.endsWith('}')) {\n"
    @"        try { d = JSON.parse(s); } catch (e) { d = null; }\n"
    @"      }\n"
    @"      if (!d) return {step: -1, text: s};\n"
    @"      const ts = (d.ts || '').toString();\n"
    @"      const lvl = (d.lvl || 'INFO').toString().toUpperCase();\n"
    @"      const tag = (d.tag || '').toString();\n"
    @"      const ev = (d.event || '').toString();\n"
    @"      const msg = (d.msg || '').toString();\n"
    @"      let tail = '';\n"
    @"      if (ev === 'step') {\n"
    @"        tail = `step=${d.step} action=${d.action || ''}`.trim();\n"
    @"      } else if (ev === 'token_usage') {\n"
    @"        tail = `req=${d.req} +in=${d.d_in} +out=${d.d_out} +cached=${d.d_cached} +total=${d.d_total} cum(in=${d.c_in} out=${d.c_out} cached=${d.c_cached} total=${d.c_total})`;\n"
    @"      } else if (d.error) {\n"
    @"        tail = `error=${(d.error || '').toString()}`;\n"
    @"      }\n"
    @"      const hdr = `${ts} [${lvl}]${tag ? ` [${tag}]` : ''}${ev ? ` [${ev}]` : ''}`.trim();\n"
    @"      const main = msg.length ? msg : ev;\n"
    @"      const text = `${hdr} ${main}${tail ? ` ${tail}` : ''}`.trim();\n"
    @"      const step = (d.step != null) ? Number(d.step) : -1;\n"
    @"      return {step: Number.isFinite(step) ? step : -1, text};\n"
    @"    }\n"
    @"    function renderLogs(){\n"
    @"      const el = document.getElementById('logs');\n"
    @"      if (!el) return;\n"
    @"      clearNode(el);\n"
    @"      if (!lastLogLines || !lastLogLines.length) return;\n"
    @"\n"
    @"      const groupMap = new Map();\n"
    @"      const groupOrder = [];\n"
    @"      for (const line of lastLogLines) {\n"
    @"        const parsed = parseLogLine(line);\n"
    @"        const k = (parsed.step >= 0) ? String(parsed.step) : 'other';\n"
    @"        if (!groupMap.has(k)) {\n"
    @"          groupMap.set(k, {key: k, step: parsed.step, lines: []});\n"
    @"          groupOrder.push(k);\n"
    @"        }\n"
    @"        groupMap.get(k).lines.push(parsed.text);\n"
    @"      }\n"
    @"\n"
    @"      const lastKey = groupOrder.length ? groupOrder[groupOrder.length - 1] : '';\n"
    @"      for (const k of groupOrder) {\n"
    @"        const g = groupMap.get(k);\n"
    @"        const card = document.createElement('details');\n"
    @"        card.className = 'step-card';\n"
    @"        if (k === lastKey) card.open = true;\n"
    @"        const sum = document.createElement('summary');\n"
    @"        if (g.step >= 0) sum.textContent = `${t('word_step')} ${g.step}`;\n"
    @"        else sum.textContent = otherLogsLabel();\n"
    @"        card.appendChild(sum);\n"
    @"        const body = document.createElement('div');\n"
    @"        body.className = 'step-body';\n"
    @"        const box = document.createElement('div');\n"
    @"        box.className = 'msg';\n"
    @"        const pre = document.createElement('pre');\n"
    @"        pre.textContent = (g.lines || []).join('\\n');\n"
    @"        box.appendChild(pre);\n"
    @"        body.appendChild(box);\n"
    @"        card.appendChild(body);\n"
    @"        el.appendChild(card);\n"
    @"      }\n"
    @"    }\n"
    @"    function renderChat(){\n"
    @"      const el = document.getElementById('chat');\n"
    @"      if (!el) return;\n"
    @"      const modeEl = document.getElementById('chat_mode');\n"
    @"      const mode = modeEl ? modeEl.value : 'structured';\n"
    @"      clearNode(el);\n"
    @"      if (!lastChatItems || !lastChatItems.length) return;\n"
    @"\n"
    @"      const showShotsEl = document.getElementById('chat_show_screenshots');\n"
    @"      const showShots = !!(showShotsEl && showShotsEl.checked);\n"
    @"\n"
    @"      const stepMap = new Map();\n"
    @"      const stepOrder = [];\n"
    @"      for (const it of lastChatItems) {\n"
    @"        const s = (it.step != null) ? Number(it.step) : NaN;\n"
    @"        if (!Number.isFinite(s)) continue;\n"
    @"        if (!stepMap.has(s)) {\n"
    @"          stepMap.set(s, {step: s, attemptMap: new Map(), attemptOrder: []});\n"
    @"          stepOrder.push(s);\n"
    @"        }\n"
    @"        const g = stepMap.get(s);\n"
    @"        const a = (it.attempt != null) ? Number(it.attempt) : 0;\n"
    @"        if (!g.attemptMap.has(a)) {\n"
    @"          g.attemptMap.set(a, {attempt: a, request: null, response: null});\n"
    @"          g.attemptOrder.push(a);\n"
    @"        }\n"
    @"        const ag = g.attemptMap.get(a);\n"
    @"        const kind = (it.kind || '').toString();\n"
    @"        if (kind === 'request') ag.request = it;\n"
    @"        else if (kind === 'response') ag.response = it;\n"
    @"      }\n"
    @"\n"
    @"      const lastStep = stepOrder.length ? stepOrder[stepOrder.length - 1] : -1;\n"
    @"      for (const step of stepOrder) {\n"
    @"        const g = stepMap.get(step);\n"
    @"        const card = document.createElement('details');\n"
    @"        card.className = 'step-card';\n"
    @"        if (step === lastStep) card.open = true;\n"
    @"\n"
    @"        const sum = document.createElement('summary');\n"
    @"        sum.textContent = `${t('word_step')} ${step}` + attemptCountLabel(g.attemptOrder.length);\n"
    @"        card.appendChild(sum);\n"
    @"\n"
    @"        const body = document.createElement('div');\n"
    @"        body.className = 'step-body';\n"
    @"\n"
    @"        if (showShots) {\n"
    @"          const ph = document.createElement('div');\n"
    @"          ph.className = 'muted';\n"
    @"          ph.textContent = screenshotPlaceholderText();\n"
    @"          const img = document.createElement('img');\n"
    @"          img.className = 'shot';\n"
    @"          img.alt = `${t('word_step')} ${step}`;\n"
    @"          img.style.display = 'none';\n"
    @"          body.appendChild(ph);\n"
    @"          body.appendChild(img);\n"
    @"          const load = () => ensureStepScreenshot(step, img, ph);\n"
    @"          card.addEventListener('toggle', () => { if (card.open) load(); });\n"
    @"          if (card.open) load();\n"
    @"        }\n"
    @"\n"
    @"        for (const a of g.attemptOrder) {\n"
    @"          const ag = g.attemptMap.get(a);\n"
    @"          appendChatMsg(body, ag.request, mode);\n"
    @"          appendChatMsg(body, ag.response, mode);\n"
    @"        }\n"
    @"\n"
    @"        card.appendChild(body);\n"
    @"        el.appendChild(card);\n"
    @"      }\n"
    @"    }\n"
    @"    async function resetAll(){\n"
    @"      await commitIME();\n"
    @"      await api('/agent/reset', 'POST');\n"
    @"      dirty = false;\n"
    @"      await refresh();\n"
    @"    }\n"
    @"    let refreshInFlight = false;\n"
    @"    async function refresh(){\n"
    @"      if (refreshInFlight) return;\n"
    @"      // Avoid UI updates while editing; iOS Safari may jump the caret/scroll when DOM updates frequently.\n"
    @"      if (isEditing() || composing) return;\n"
    @"      refreshInFlight = true;\n"
    @"      try {\n"
    @"        lastRunnerOk = false;\n"
    @"        lastRunnerError = '';\n"
    @"        try {\n"
    @"          await api('/status');\n"
    @"          lastRunnerOk = true;\n"
    @"        } catch (e) {\n"
    @"          lastRunnerOk = false;\n"
    @"          lastRunnerError = (e && e.message) ? e.message : String(e);\n"
    @"        }\n"
    @"\n"
    @"        lastStatus = null;\n"
    @"        lastStatusError = '';\n"
    @"        lastStatusCode = 0;\n"
    @"\n"
    @"        const st = await api('/agent/status');\n"
    @"        lastStatus = st;\n"
    @"        lastTokenUsage = tokenUsageFromStatus();\n"
    @"        lastStatusCode = 200;\n"
    @"        document.getElementById('status').textContent = JSON.stringify(st, null, 2);\n"
    @"        const notes = st.notes || '';\n"
    @"        document.getElementById('notes').textContent = notes;\n"
    @"        if (!dirty && !isEditing()) {\n"
    @"          fillUI((st.config)||{});\n"
    @"        }\n"
    @"        if (!eventsReady) {\n"
    @"          const chat = await api('/agent/chat');\n"
    @"          lastChatItems = (chat.items || []);\n"
    @"          renderChat();\n"
    @"          const logs = await api('/agent/logs');\n"
    @"          lastLogLines = (logs.lines || []);\n"
    @"          renderLogs();\n"
    @"        }\n"
    @"      } catch (e) {\n"
    @"        lastStatus = null;\n"
    @"        lastStatusCode = (e && typeof e.status === 'number') ? e.status : 0;\n"
    @"        lastStatusError = (e && e.message) ? e.message : String(e);\n"
    @"        document.getElementById('status').textContent = lastStatusError;\n"
    @"        document.getElementById('notes').textContent = '';\n"
    @"        lastLogLines = [];\n"
    @"        renderLogs();\n"
    @"        lastChatItems = [];\n"
    @"        renderChat();\n"
    @"      }\n"
	    @"      } finally {\n"
	    @"        refreshInFlight = false;\n"
    @"        updateReadinessUI();\n"
	    @"      }\n"
	    @"    }\n"
    @"    async function saveCfg(){\n"
    @"      await commitIME();\n"
    @"      if (!validateBeforeStart()) return;\n"
    @"      await api('/agent/config', 'POST', cfgFromUI());\n"
    @"      dirty = false;\n"
    @"      await refresh();\n"
    @"    }\n"
    @"    async function start(){\n"
    @"      await commitIME();\n"
    @"      if (!validateBeforeStart()) return;\n"
    @"      const resp = await api('/agent/start', 'POST', cfgFromUI());\n"
    @"      dirty = false;\n"
    @"      await refresh();\n"
    @"      if (resp && resp.ok === false && resp.error) {\n"
    @"        setFormError([resp.error]);\n"
    @"      }\n"
    @"    }\n"
	    @"    async function stop(){\n"
	    @"      await api('/agent/stop', 'POST');\n"
	    @"      await refresh();\n"
	    @"    }\n"
    @"    function isPageVisible(){ return !document.hidden; }\n"
    @"    function closeEvents(){\n"
    @"      if (!events) return;\n"
    @"      try { events.close(); } catch (e) {}\n"
    @"      events = null;\n"
    @"      eventsReady = false;\n"
    @"    }\n"
    @"    function stopPolling(){\n"
    @"      if (!pollTimer) return;\n"
    @"      try { clearInterval(pollTimer); } catch (e) {}\n"
    @"      pollTimer = null;\n"
    @"    }\n"
    @"    function startPolling(){\n"
    @"      if (pollTimer) return;\n"
    @"      pollTimer = setInterval(() => {\n"
    @"        if (!isPageVisible()) return;\n"
    @"        if (events) return;\n"
    @"        if (lastStatus && lastStatus.running) refresh();\n"
    @"        else stopPolling();\n"
    @"      }, __DEFAULT_REFRESH_INTERVAL_MS__);\n"
    @"    }\n"
    @"    function updateAutoUpdates(){\n"
    @"      if (events) {\n"
    @"        stopPolling();\n"
    @"        return;\n"
    @"      }\n"
    @"      if (lastStatus && lastStatus.running) startPolling();\n"
    @"      else stopPolling();\n"
    @"    }\n"
    @"    let renderTimer = null;\n"
    @"    function scheduleRender(){\n"
    @"      if (renderTimer) return;\n"
    @"      renderTimer = setTimeout(() => {\n"
    @"        renderTimer = null;\n"
    @"        if (isEditing() || composing) {\n"
    @"          pendingAutoRefresh = true;\n"
    @"          return;\n"
    @"        }\n"
    @"        renderChat();\n"
    @"        renderLogs();\n"
    @"        updateReadinessUI();\n"
    @"      }, 80);\n"
    @"    }\n"
    @"    function maybeApplyPendingAutoRefresh(){\n"
    @"      if (!pendingAutoRefresh) return;\n"
    @"      if (isEditing() || composing) return;\n"
    @"      pendingAutoRefresh = false;\n"
    @"      try {\n"
    @"        renderChat();\n"
    @"        renderLogs();\n"
    @"        updateReadinessUI();\n"
    @"      } catch (e) {}\n"
    @"      refresh();\n"
    @"    }\n"
    @"    function applyStatusFromPush(st){\n"
    @"      if (!st) return;\n"
    @"      lastStatus = st;\n"
    @"      lastTokenUsage = tokenUsageFromStatus();\n"
    @"      lastStatusError = '';\n"
    @"      lastStatusCode = 200;\n"
    @"      if (isEditing() || composing) {\n"
    @"        pendingAutoRefresh = true;\n"
    @"        return;\n"
    @"      }\n"
    @"      document.getElementById('status').textContent = JSON.stringify(st, null, 2);\n"
    @"      document.getElementById('notes').textContent = st.notes || '';\n"
    @"      if (!dirty && !isEditing()) {\n"
    @"        fillUI((st.config)||{});\n"
    @"      }\n"
    @"      updateReadinessUI();\n"
    @"    }\n"
    @"    function applySnapshotFromPush(snap){\n"
    @"      if (!snap) return;\n"
    @"      if (snap.status) {\n"
    @"        lastRunnerOk = true;\n"
    @"        lastRunnerError = '';\n"
    @"        applyStatusFromPush(snap.status);\n"
    @"      }\n"
    @"      if (Array.isArray(snap.logs)) {\n"
    @"        lastLogLines = snap.logs.slice();\n"
    @"      } else if (snap.logs && Array.isArray(snap.logs.lines)) {\n"
    @"        lastLogLines = snap.logs.lines.slice();\n"
    @"      }\n"
    @"      if (Array.isArray(snap.chat)) {\n"
    @"        lastChatItems = snap.chat.slice();\n"
    @"      } else if (snap.chat && Array.isArray(snap.chat.items)) {\n"
    @"        lastChatItems = snap.chat.items.slice();\n"
    @"      }\n"
    @"      eventsReady = true;\n"
    @"      scheduleRender();\n"
    @"      updateAutoUpdates();\n"
    @"    }\n"
    @"    function appendLogLineFromPush(line){\n"
    @"      const s = (line || '').toString();\n"
    @"      if (!s.length) return;\n"
    @"      lastLogLines.push(s);\n"
    @"      while (lastLogLines.length > MAX_LOG_LINES) lastLogLines.shift();\n"
    @"      try {\n"
    @"        const d = JSON.parse(s);\n"
    @"        if (d && d.event === 'token_usage') {\n"
    @"          lastTokenUsage = {\n"
    @"            requests: Number(d.req || 0),\n"
    @"            input: Number(d.c_in || 0),\n"
    @"            output: Number(d.c_out || 0),\n"
    @"            cached: Number(d.c_cached || 0),\n"
    @"            total: Number(d.c_total || 0),\n"
    @"          };\n"
    @"        }\n"
    @"      } catch (e) {}\n"
    @"      scheduleRender();\n"
    @"    }\n"
    @"    function chatHardLimit(){\n"
    @"      try {\n"
    @"        const ms = Number(((lastStatus && lastStatus.config) ? lastStatus.config.max_steps : 0) || 0);\n"
    @"        const hard = Math.max(200, (Number.isFinite(ms) && ms > 0 ? ms : 60) * 8);\n"
    @"        return hard;\n"
    @"      } catch (e) { return 480; }\n"
    @"    }\n"
    @"    function appendChatItemFromPush(it){\n"
    @"      if (!it) return;\n"
    @"      lastChatItems.push(it);\n"
    @"      const hard = chatHardLimit();\n"
    @"      while (lastChatItems.length > hard) lastChatItems.shift();\n"
    @"      scheduleRender();\n"
    @"    }\n"
    @"    function connectEvents(){\n"
    @"      if (!window.EventSource) return false;\n"
    @"      if (events) return true;\n"
    @"      try {\n"
    @"        const u = new URL('/agent/events', window.location.href);\n"
    @"        u.searchParams.set('include_default_system_prompt','0');\n"
    @"        events = new EventSource(u.toString());\n"
    @"      } catch (e) {\n"
    @"        events = null;\n"
    @"        return false;\n"
    @"      }\n"
    @"      events.addEventListener('snapshot', (ev) => {\n"
    @"        try { applySnapshotFromPush(JSON.parse((ev && ev.data) ? ev.data : '{}')); } catch (e) {}\n"
    @"      });\n"
    @"      events.addEventListener('status', (ev) => {\n"
    @"        try { applyStatusFromPush(JSON.parse((ev && ev.data) ? ev.data : '{}')); } catch (e) {}\n"
    @"      });\n"
    @"      events.addEventListener('log', (ev) => {\n"
    @"        appendLogLineFromPush((ev && ev.data) ? ev.data : '');\n"
    @"      });\n"
    @"      events.addEventListener('chat', (ev) => {\n"
    @"        try { appendChatItemFromPush(JSON.parse((ev && ev.data) ? ev.data : '{}')); } catch (e) {}\n"
    @"      });\n"
    @"      events.addEventListener('ping', (_ev) => {});\n"
    @"      events.onerror = (_ev) => {\n"
    @"        closeEvents();\n"
    @"        updateAutoUpdates();\n"
    @"      };\n"
    @"      return true;\n"
    @"    }\n"
    @"    async function startAutoUpdates(forceRefresh){\n"
    @"      if (!isPageVisible()) return;\n"
    @"      if (isEditing() || composing) { pendingAutoRefresh = true; return; }\n"
    @"      const ok = connectEvents();\n"
    @"      if (!ok || forceRefresh) {\n"
    @"        await refresh();\n"
    @"      }\n"
    @"      updateAutoUpdates();\n"
    @"    }\n"
    @"    document.addEventListener('focusout', () => { setTimeout(maybeApplyPendingAutoRefresh, 0); });\n"
    @"    document.addEventListener('visibilitychange', () => {\n"
    @"      if (document.hidden) {\n"
    @"        closeEvents();\n"
    @"        stopPolling();\n"
    @"      } else {\n"
    @"        startAutoUpdates(true);\n"
    @"      }\n"
    @"    });\n"
    @"    applyI18n();\n"
    @"    initDirtyTracking();\n"
    @"    stripTokenFromURL();\n"
    @"    {\n"
    @"      const modeEl = document.getElementById('chat_mode');\n"
    @"      if (modeEl) {\n"
    @"        const saved = localStorage.getItem('ondevice_agent_chat_mode');\n"
    @"        if (saved) modeEl.value = saved;\n"
    @"        modeEl.addEventListener('change', () => {\n"
    @"          localStorage.setItem('ondevice_agent_chat_mode', modeEl.value);\n"
    @"          renderChat();\n"
    @"        });\n"
    @"      }\n"
    @"    }\n"
    @"    {\n"
    @"      const cb = document.getElementById('chat_show_screenshots');\n"
    @"      if (cb) {\n"
    @"        const saved = localStorage.getItem('ondevice_agent_chat_show_screenshots');\n"
    @"        if (saved === '1') cb.checked = true;\n"
    @"        cb.addEventListener('change', () => {\n"
    @"          localStorage.setItem('ondevice_agent_chat_show_screenshots', cb.checked ? '1' : '');\n"
    @"          renderChat();\n"
    @"        });\n"
    @"      }\n"
    @"    }\n"
    @"    if (document.getElementById('system_prompt') && !document.getElementById('system_prompt').value) {\n"
    @"      document.getElementById('system_prompt').value = DEFAULT_SYSTEM_PROMPT;\n"
    @"    }\n"
    @"    startAutoUpdates(true);\n"
    @"  </script>\n";

  static NSString *const kOnDeviceAgentPageTail =
    @"</body>\n"
    @"</html>\n";

  NSString *html = [@[
    kOnDeviceAgentPageHTMLHead,
    kOnDeviceAgentPageCSS,
    kOnDeviceAgentPageBody,
    kOnDeviceAgentPageJS,
    kOnDeviceAgentPageTail,
  ] componentsJoinedByString:@""];

  NSString *dateZh = OnDeviceAgentFormattedDateZH();
  NSString *dateEn = OnDeviceAgentFormattedDateEN();
  NSString *defaultSystemPrompt = OnDeviceAgentDefaultSystemPromptTemplate();
  NSString *defaultMaxSteps = [NSString stringWithFormat:@"%ld", (long)kOnDeviceAgentDefaultMaxSteps];
  NSString *defaultMaxCompletionTokens = [NSString stringWithFormat:@"%ld", (long)kOnDeviceAgentDefaultMaxCompletionTokens];
  NSString *defaultTimeoutSeconds = [NSString stringWithFormat:@"%g", kOnDeviceAgentDefaultTimeoutSeconds];
  NSString *defaultStepDelaySeconds = [NSString stringWithFormat:@"%g", kOnDeviceAgentDefaultStepDelaySeconds];
  NSString *defaultRefreshIntervalMs = [NSString stringWithFormat:@"%ld", (long)kOnDeviceAgentDefaultRefreshIntervalMs];
  html = [html stringByReplacingOccurrencesOfString:@"__DATE_ZH_EXAMPLE__" withString:OnDeviceAgentHTMLEscape(dateZh)];
  html = [html stringByReplacingOccurrencesOfString:@"__DATE_EN_EXAMPLE__" withString:OnDeviceAgentHTMLEscape(dateEn)];
  html = [html stringByReplacingOccurrencesOfString:@"__DEFAULT_SYSTEM_PROMPT_JSON__" withString:OnDeviceAgentJSONStringLiteral(defaultSystemPrompt)];
  html = [html stringByReplacingOccurrencesOfString:@"__DEFAULT_MAX_STEPS__" withString:defaultMaxSteps];
  html = [html stringByReplacingOccurrencesOfString:@"__DEFAULT_MAX_COMPLETION_TOKENS__" withString:defaultMaxCompletionTokens];
  html = [html stringByReplacingOccurrencesOfString:@"__DEFAULT_TIMEOUT_SECONDS__" withString:defaultTimeoutSeconds];
  html = [html stringByReplacingOccurrencesOfString:@"__DEFAULT_STEP_DELAY_SECONDS__" withString:defaultStepDelaySeconds];
  html = [html stringByReplacingOccurrencesOfString:@"__DEFAULT_REFRESH_INTERVAL_MS__" withString:defaultRefreshIntervalMs];
  return html;
}

static NSString *OnDeviceAgentEditPageHTML(void)
{
  static NSString *const kOnDeviceAgentEditPageHead =
    @"<!doctype html>\n"
    @"<html>\n"
    @"<head>\n"
    @"  <meta charset=\"utf-8\" />\n"
    @"  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, viewport-fit=cover\" />\n"
    @"  <title>iOS WDA On‑Device Agent Editor</title>\n"
    @"  <style>\n";

  static NSString *const kOnDeviceAgentEditPageCSS =
    @"    :root{color-scheme:light dark;--bg:#fff;--fg:#111;--muted:#666;--card:#f6f6f6;--border:#ccc;--primary:#0a84ff;--danger:#ff3b30;--radius:12px;}\n"
    @"    @media (prefers-color-scheme: dark){:root{--bg:#0b0b0c;--fg:#f2f2f2;--muted:#b0b0b0;--card:#1c1c1e;--border:#3a3a3c;--primary:#0a84ff;--danger:#ff453a;}}\n"
    @"    html,body{height:100%;}\n"
    @"    body{margin:0;background:var(--bg);color:var(--fg);height:100dvh;max-height:100dvh;box-sizing:border-box;padding:16px;padding-left:max(16px,env(safe-area-inset-left));padding-right:max(16px,env(safe-area-inset-right));padding-top:max(16px,env(safe-area-inset-top));padding-bottom:max(16px,env(safe-area-inset-bottom));display:flex;flex-direction:column;gap:10px;font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica,Arial,sans-serif;}\n"
    @"    .bar{display:flex;align-items:center;justify-content:space-between;gap:10px;}\n"
    @"    .title{font-weight:600;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;}\n"
    @"    .muted{color:var(--muted);font-size:13px;line-height:1.45;}\n"
    @"    .check{display:flex;align-items:center;gap:10px;user-select:none;}\n"
    @"    .check input{width:auto;transform:scale(1.15);}\n"
    @"    button{min-height:40px;padding:8px 12px;border:0;border-radius:12px;}\n"
    @"    .primary{background:var(--primary);color:#fff;}\n"
    @"    .ghost{background:var(--card);color:inherit;border:1px solid var(--border);}\n"
    @"    textarea{width:100%;flex:1 1 auto;min-height:0;padding:10px 12px;border:1px solid var(--border);border-radius:var(--radius);box-sizing:border-box;font-size:16px;line-height:1.35;background:var(--card);color:inherit;resize:none;}\n"
    @"    textarea:focus{outline:none;border-color:var(--primary);box-shadow:0 0 0 3px rgba(10,132,255,0.25);}\n"
    @"    .mono{font-family:ui-monospace,SFMono-Regular,Menlo,Monaco,Consolas,\"Liberation Mono\",\"Courier New\",monospace;}\n"
    @"  </style>\n";

	  static NSString *const kOnDeviceAgentEditPageBody =
	    @"</head>\n"
	    @"<body>\n"
	    @"  <div class=\"bar\">\n"
	    @"    <button class=\"ghost\" onclick=\"goBack()\" data-i18n=\"btn_back\">Back</button>\n"
	    @"    <div id=\"title\" class=\"title\">Editor</div>\n"
	    @"    <button id=\"restore_default\" class=\"ghost\" style=\"display:none\" onclick=\"restoreDefault()\" data-i18n=\"btn_restore_default\">Restore default</button>\n"
	    @"    <button class=\"primary\" onclick=\"saveAndClose()\" data-i18n=\"btn_done\">Done</button>\n"
	    @"  </div>\n"
	    @"  <div id=\"hint\" class=\"muted\"></div>\n"
	    @"  <label id=\"custom_row\" class=\"check muted\" style=\"display:none\"><input type=\"checkbox\" id=\"use_custom_system_prompt\" /> <span data-i18n=\"cb_use_custom_system_prompt\">Use custom system prompt</span></label>\n"
	    @"  <textarea id=\"text\" placeholder=\"\"></textarea>\n"
	    @"  <script>\n";

	  static NSString *const kOnDeviceAgentEditPageJS =
	    @"    const DEFAULT_SYSTEM_PROMPT = __DEFAULT_SYSTEM_PROMPT_JSON__;\n"
	    @"    const LANG = ((navigator.language || '').toLowerCase().startsWith('zh')) ? 'zh' : 'en';\n"
	    @"    const I18N = {\n"
	    @"      en: {\n"
	    @"        btn_back: 'Back',\n"
	    @"        btn_restore_default: 'Restore default',\n"
	    @"        btn_done: 'Done',\n"
	    @"        cb_use_custom_system_prompt: 'Use custom system prompt',\n"
	    @"        title_task: 'Task',\n"
	    @"        title_system_prompt: 'System Prompt',\n"
	    @"        title_editor: 'Editor',\n"
	    @"        hint_task: 'Edit the task description.',\n"
	    @"        hint_system_prompt: 'Custom system prompt only takes effect when enabled.',\n"
	    @"        hint_unknown: 'Unknown target.',\n"
	    @"      },\n"
	    @"      zh: {\n"
	    @"        btn_back: '返回',\n"
	    @"        btn_restore_default: '恢复默认',\n"
	    @"        btn_done: '完成',\n"
	    @"        cb_use_custom_system_prompt: '使用自定义系统提示词',\n"
	    @"        title_task: '任务',\n"
	    @"        title_system_prompt: '系统提示词',\n"
	    @"        title_editor: '编辑',\n"
	    @"        hint_task: '编辑任务描述。',\n"
	    @"        hint_system_prompt: '自定义系统提示词仅在勾选后生效。',\n"
	    @"        hint_unknown: '未知目标。',\n"
	    @"      }\n"
	    @"    };\n"
	    @"    function t(key){\n"
	    @"      const table = I18N[LANG] || I18N.en;\n"
	    @"      return (table && table[key]) ? table[key] : ((I18N.en && I18N.en[key]) ? I18N.en[key] : key);\n"
	    @"    }\n"
	    @"    function applyI18n(){\n"
	    @"      const nodes = document.querySelectorAll('[data-i18n]');\n"
	    @"      for (const el of nodes) {\n"
	    @"        const key = el.getAttribute('data-i18n') || '';\n"
	    @"        if (!key) continue;\n"
	    @"        el.textContent = t(key);\n"
	    @"      }\n"
	    @"    }\n"
	    @"    const qs = new URLSearchParams(window.location.search || '');\n"
	    @"    const target = (qs.get('target') || '').toString();\n"
	    @"    let composing = false;\n"
    @"    function isEditing(){\n"
    @"      const el = document.activeElement;\n"
    @"      if (!el || !el.tagName) return false;\n"
    @"      const tag = el.tagName.toLowerCase();\n"
    @"      return tag === 'input' || tag === 'textarea';\n"
    @"    }\n"
    @"    async function commitIME(){\n"
    @"      if (isEditing() && document.activeElement) {\n"
    @"        try { document.activeElement.blur(); } catch (e) {}\n"
    @"        await new Promise(r => setTimeout(r, 50));\n"
    @"      }\n"
    @"      if (composing) {\n"
    @"        await new Promise(r => setTimeout(r, 50));\n"
    @"      }\n"
    @"    }\n"
    @"    function stripTokenFromURL(){\n"
    @"      // Agent Token should never live in the URL longer than the initial page load.\n"
    @"      try {\n"
    @"        const qs = new URLSearchParams(window.location.search || '');\n"
    @"        if (!qs.has('token')) return;\n"
    @"        qs.delete('token');\n"
    @"        const next = window.location.pathname + (qs.toString() ? ('?' + qs.toString()) : '') + (window.location.hash || '');\n"
    @"        window.history.replaceState({}, '', next);\n"
    @"      } catch (e) {}\n"
    @"    }\n"
    @"    async function api(path, method, body){\n"
    @"      const opts = {method: method || 'GET', credentials: 'same-origin'};\n"
    @"      const headers = {};\n"
    @"      if (body){ headers['Content-Type'] = 'application/json'; opts.body = JSON.stringify(body); }\n"
    @"      if (Object.keys(headers).length > 0) { opts.headers = headers; }\n"
    @"      const r = await fetch(path, opts);\n"
    @"      const j = await r.json().catch(() => ({}));\n"
    @"      if (!r.ok) {\n"
    @"        const msg = ((j.value && j.value.error) || j.error || `HTTP ${r.status}`);\n"
    @"        throw new Error(msg);\n"
    @"      }\n"
    @"      return j.value || {};\n"
    @"    }\n"
    @"    function updateViewport(){\n"
    @"      const vv = window.visualViewport;\n"
    @"      if (!vv) return;\n"
    @"      document.body.style.height = vv.height + 'px';\n"
    @"      document.body.style.transform = `translateY(${vv.offsetTop || 0}px)`;\n"
    @"    }\n"
	    @"    async function load(){\n"
	    @"      updateViewport();\n"
	    @"      applyI18n();\n"
	    @"      const st = await api('/agent/status');\n"
	    @"      const cfg = st.config || {};\n"
    @"      const titleEl = document.getElementById('title');\n"
    @"      const hintEl = document.getElementById('hint');\n"
    @"      const ta = document.getElementById('text');\n"
    @"      const customRow = document.getElementById('custom_row');\n"
    @"      const useCustom = document.getElementById('use_custom_system_prompt');\n"
	    @"      const restoreBtn = document.getElementById('restore_default');\n"
	    @"      if (!titleEl || !hintEl || !ta || !customRow || !useCustom || !restoreBtn) return;\n"
	    @"      if (target === 'task') {\n"
	    @"        titleEl.textContent = t('title_task');\n"
	    @"        hintEl.textContent = t('hint_task');\n"
	    @"        ta.className = '';\n"
	    @"        ta.value = (cfg.task || '').toString();\n"
	    @"        customRow.style.display = 'none';\n"
	    @"        restoreBtn.style.display = 'none';\n"
	    @"      } else if (target === 'system_prompt') {\n"
	    @"        titleEl.textContent = t('title_system_prompt');\n"
	    @"        hintEl.textContent = t('hint_system_prompt');\n"
	    @"        ta.className = 'mono';\n"
	    @"        const sp = (cfg.system_prompt || '').toString();\n"
    @"        ta.value = sp.length ? sp : DEFAULT_SYSTEM_PROMPT;\n"
    @"        customRow.style.display = '';\n"
	    @"        useCustom.checked = !!cfg.use_custom_system_prompt;\n"
	    @"        restoreBtn.style.display = '';\n"
	    @"      } else {\n"
	    @"        titleEl.textContent = t('title_editor');\n"
	    @"        hintEl.textContent = t('hint_unknown');\n"
	    @"        ta.className = 'mono';\n"
	    @"        ta.value = '';\n"
    @"        customRow.style.display = 'none';\n"
    @"        restoreBtn.style.display = 'none';\n"
    @"      }\n"
    @"      ta.addEventListener('compositionstart', () => { composing = true; });\n"
    @"      ta.addEventListener('compositionend', () => { composing = false; });\n"
    @"      try { ta.focus(); } catch (e) {}\n"
    @"    }\n"
    @"    function goBack(){ window.location.href = '/agent'; }\n"
    @"    function restoreDefault(){\n"
    @"      if (target !== 'system_prompt') return;\n"
    @"      const ta = document.getElementById('text');\n"
    @"      if (!ta) return;\n"
    @"      ta.value = DEFAULT_SYSTEM_PROMPT;\n"
    @"    }\n"
    @"    async function saveAndClose(){\n"
    @"      await commitIME();\n"
    @"      const ta = document.getElementById('text');\n"
    @"      if (!ta) return;\n"
    @"      const payload = {};\n"
    @"      if (target === 'task') {\n"
    @"        payload.task = (ta.value || '').toString();\n"
    @"      } else if (target === 'system_prompt') {\n"
    @"        payload.system_prompt = (ta.value || '').toString();\n"
    @"        const useCustom = document.getElementById('use_custom_system_prompt');\n"
    @"        payload.use_custom_system_prompt = !!(useCustom && useCustom.checked);\n"
    @"      }\n"
    @"      if (Object.keys(payload).length) {\n"
    @"        await api('/agent/config', 'POST', payload);\n"
    @"      }\n"
    @"      goBack();\n"
    @"    }\n"
    @"    if (window.visualViewport) {\n"
    @"      try {\n"
    @"        window.visualViewport.addEventListener('resize', updateViewport);\n"
    @"        window.visualViewport.addEventListener('scroll', updateViewport);\n"
    @"      } catch (e) {}\n"
    @"    }\n"
    @"    stripTokenFromURL();\n"
    @"    load();\n"
    @"  </script>\n";

  static NSString *const kOnDeviceAgentEditPageTail =
    @"</body>\n"
    @"</html>\n";

  NSString *html = [@[
    kOnDeviceAgentEditPageHead,
    kOnDeviceAgentEditPageCSS,
    kOnDeviceAgentEditPageBody,
    kOnDeviceAgentEditPageJS,
    kOnDeviceAgentEditPageTail,
  ] componentsJoinedByString:@""];

  NSString *defaultSystemPrompt = OnDeviceAgentDefaultSystemPromptTemplate();
  html = [html stringByReplacingOccurrencesOfString:@"__DEFAULT_SYSTEM_PROMPT_JSON__" withString:OnDeviceAgentJSONStringLiteral(defaultSystemPrompt)];
  return html;
}

