#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Usage:
  bash scripts/configure_wda_signing.sh --team-id <TEAMID> --bundle-prefix <com.your.prefix> [--wda-dir <path>]

What this does (local only):
  1) Updates WebDriverAgent bundle identifiers from "com.facebook.*" to "<com.your.prefix>.*"
  2) Writes a signing xcconfig (DEVELOPMENT_TEAM) and includes it from WDA config files

Notes:
  - This modifies files under third_party/WebDriverAgent (git submodule working tree).
  - Your TEAMID is written into a local xcconfig file inside the submodule. Do NOT commit it.
  - You still need to sign in to Xcode with your Apple ID at least once so Xcode can generate
    certificates/provisioning profiles (Personal Team is fine).
EOF
}

team_id=""
bundle_prefix=""
wda_dir=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --team-id)
      team_id="${2:-}"; shift 2 ;;
    --bundle-prefix)
      bundle_prefix="${2:-}"; shift 2 ;;
    --wda-dir)
      wda_dir="${2:-}"; shift 2 ;;
    -h|--help)
      usage; exit 0 ;;
    *)
      echo "Unknown argument: $1" >&2
      usage
      exit 2
      ;;
  esac
done

if [[ -z "$team_id" || -z "$bundle_prefix" ]]; then
  echo "Missing --team-id and/or --bundle-prefix" >&2
  usage
  exit 2
fi

bundle_prefix="${bundle_prefix%.}"

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "$script_dir/.." && pwd)"

if [[ -z "$wda_dir" ]]; then
  wda_dir="$repo_root/third_party/WebDriverAgent"
fi

pbxproj="$wda_dir/WebDriverAgent.xcodeproj/project.pbxproj"
if [[ ! -f "$pbxproj" ]]; then
  echo "WebDriverAgent project.pbxproj not found at: $pbxproj" >&2
  echo "Tip: run 'git submodule update --init --recursive' in repo root." >&2
  exit 2
fi

configs_dir="$wda_dir/Configurations"
if [[ ! -d "$configs_dir" ]]; then
  echo "WDA Configurations dir not found at: $configs_dir" >&2
  exit 2
fi

echo "[1/3] Updating bundle identifiers (PRODUCT_BUNDLE_IDENTIFIER) ..."
tmp_pbx="$(mktemp)"
BUNDLE_PREFIX="$bundle_prefix" perl -pe '
  my $p = $ENV{BUNDLE_PREFIX};
  s/(PRODUCT_BUNDLE_IDENTIFIER\s*=\s*)com\.facebook(\.[^;]+;)/$1$p$2/g;
' "$pbxproj" >"$tmp_pbx"
mv "$tmp_pbx" "$pbxproj"

echo "[2/3] Writing signing config xcconfig (DEVELOPMENT_TEAM=$team_id) ..."
signing_cfg="$configs_dir/OnDeviceAgentSigning.xcconfig"
cat >"$signing_cfg" <<EOF
// Auto-generated by scripts/configure_wda_signing.sh
// Local-only: do NOT commit your TEAMID.
DEVELOPMENT_TEAM = $team_id
CODE_SIGN_STYLE = Automatic
PROVISIONING_PROFILE_SPECIFIER =
EOF

echo "[3/3] Ensuring xcconfig includes ..."
include_line='#include "OnDeviceAgentSigning.xcconfig"'
for f in IOSSettings.xcconfig IOSTestSettings.xcconfig TVOSSettings.xcconfig TVOSTestSettings.xcconfig; do
  cfg="$configs_dir/$f"
  if [[ ! -f "$cfg" ]]; then
    continue
  fi
  if grep -qF "$include_line" "$cfg" 2>/dev/null; then
    continue
  fi
  tmp_cfg="$(mktemp)"
  {
    echo "$include_line"
    cat "$cfg"
  } >"$tmp_cfg"
  mv "$tmp_cfg" "$cfg"
done

echo
echo "Done."
echo "  WDA dir:        $wda_dir"
echo "  Team ID:        $team_id"
echo "  Bundle prefix:  $bundle_prefix"
echo
echo "Next:"
echo "  1) Apply patch: bash scripts/apply_patch_to_wda.sh"
echo "  2) Install:     bash scripts/install_wda_prepared_runner.sh --device <UDID>"
